### ISSUE TITLE
howto add a package into phi+docker+django?

### ISSUE THREAD

**Issue by j2l** [phidatahq/phidata#1025]
Hello again,
I successfully run `phi ws up` to get the 2 containers running.
when I pip install a django package from the container, it works fine ... until I shut the container down.
My host venv has the package installed, but phi doesn't seem to add it to the image for django (venv is not the same in the container, using docker image's python).
I also added it in requirements.txt hoping that `phi ws up` would reinstall each time, no luck so far.

How to add a django package to a phi docker stack?
Thank you

**Comment by ysolanky** [comment]
Hello!
You would need to build a custom image after making the changes. Here are the [docs](https://docs.phidata.com/templates/how-to/development-app)

**Comment by j2l** [comment]
Thanks! I'll have a look
