### ISSUE TITLE
Can we use CSV based knowledge

### ISSUE THREAD

**Issue by cfbreathing** [phidatahq/phidata#1034]
I tried your agent and it's just too powerful. But I have a question, that is in the future can there be CSV assistant to read my local csv file and answer questions, just like pdf assistant.

**Comment by vishwajeetdabholkar** [comment]
Hi @cfbreathing ,
here is an example to use SQL assistant on json files : cookbook/examples/sql/assistant.py
https://github.com/phidatahq/phidata/blob/main/cookbook/examples/sql/assistant.py

It is an example for JSON but you should be easily build logic for csv too using this

**Comment by ysolanky** [comment]
Hey @cfbreathing I have a PR out for using CSV files as a knowledge base. Please feel free to test it out: https://github.com/phidatahq/phidata/pull/1031

**Comment by ysolanky** [comment]
@cfbreathing please upgrade to [v2.4.24](https://github.com/phidatahq/phidata/releases/tag/v2.4.24. It now includes CSV Knowledge base

**Comment by cfbreathing** [comment]
Thank you so much for implementing this feature! I can now build my phidata using csv!🙂
