### ISSUE TITLE
框架会自动保存数据到PostgreSQL数据库吗？

### ISSUE THREAD

**Issue by 812781385** [phidatahq/phidata#1035]
你好，我的外国朋友！

我在使用这个例子：Assistant with Memory, Knowledge & Tools ，https://docs.phidata.com/basics

我创建了数据库和表，可是我不知道改创建哪些字段和属性，还是说框架自动帮我创建呢？

**Comment by ysolanky** [comment]
Hello @812781385!

Yes, you do not need to create any tables manually
