### ISSUE TITLE
Feature Request: Context-aware tool calls

### ISSUE THREAD

**Issue by z404** [phidatahq/phidata#1037]
Is it feasible to optionally create context-aware tool calls, such that metadata is passed to any tool call that is done by the llm wherein the executing conversation thread passes the conversation ID, and/or the tool call ID (and/or any other information available to the assistant object that one feels would be useful for the tool to have as context) to the tool's function call?

Happy to further explain the usecase that this would help with, if required.

**Comment by jacobweiss2305** [comment]
@z404 join the discord lets chat about this https://discord.com/invite/4MtYHHrgA8
