### ISSUE TITLE
Gradio demo on Spaces

### ISSUE THREAD

**Issue by yvrjsharma** [phidatahq/phidata#105]
Kudos for building Phidata. It would be great to have a hosted gradio app on Spaces as well. Are there any plans?

**Comment by ashpreetbedi** [comment]
@yvrjsharma this is so cool! yes lets build one

**Comment by yvrjsharma** [comment]
Awesome, let us know if you need any help from us at huggingface-gradio!

**Comment by jacobweiss2305** [comment]
Added to feature request
