### ISSUE TITLE
Assistant max function calling

### ISSUE THREAD

**Issue by jacobweiss2305** [phidatahq/phidata#106]
Is there a way to max out the phidata python assistant on how many steps it can take? I am trying to control for infinite loops.

**Comment by ashpreetbedi** [comment]
@jacobweiss2305 setting `Assistant(..., tool_call_limit=5)`, after the `tool_call_limit` is reached it will deactivate the function calls

**Comment by ashpreetbedi** [comment]
We currently set it to 20, but imo that number is bit high, somewhere around 7-10 is a good number
