### ISSUE TITLE
Question about PDF AI at https://pdf.aidev.run/

### ISSUE THREAD

**Issue by aamirahmed2004** [phidatahq/phidata#1087]
Just a question, wasn't sure where else to ask: Wanted to ask about which document parser, embedding model, and model that is used for the sample chatbot at https://pdf.aidev.run/, since it seems to perform better on tables and other tricky details than the starter app in phidata/cookbook/llms/ollama/rag used with Llama 3 8b + nomic-embed + default PDF parser provided (PyPDF I believe). Still learning RAG and would love to learn about good open-source options.

**Comment by ysolanky** [comment]
Hello @aamirahmed2004 ! The LLM being used for pdf Assistant is `gpt-4-turbo-preview` and the embedding model is `text-embedding-3-small`. Both by OpenAI. You can find the code for the pdf assistant [here](https://github.com/phidatahq/ai-cookbook/tree/main/pdf_ai). 

Please feel free to connect with us on Discord: https://discord.gg/x8NjBGDK
