### ISSUE TITLE
'save_output_to_file = True' does not save the FULL chat history??

### ISSUE THREAD

**Issue by SamuelDevdas** [phidatahq/phidata#1100]
### SCREENSHOTS

![encodin-error2](https://github.com/user-attachments/assets/3398dff6-813b-463e-a06a-06579a333212)
![save-history-file-issue](https://github.com/user-attachments/assets/9d8eb36b-ba16-4dc4-9fdb-31f1ec1b7645)
**Description**:

I'm encountering an issue where the `save_output_to_file = True` option does not seem to save the full chat history as expected. 

### Steps to Reproduce:

1. Set the `save_output_to_file` parameter in the assistant configuration as follows:
   ```python
   save_output_to_file="chat_history.md"
   ```
Note: disregard the timestamp fstring in the image attached, that is just to keep track of files

2. Run the assistant and engage in multiple interactions.

### Expected Behavior:

The full chat history should be saved to the specified file, capturing all interactions from start to finish.

### Actual Behavior:

Only the assistants latest reply is saved, and previous interactions (**including user message**) seem to be missing from the file.

### Configuration Details:

- `add_chat_history_to_prompt=True`
- `num_history_messages=10`

Attached are screenshots of the issue:

1. The setup of the assistant configuration.
2. The title of the issue that illustrates the problem.

Please let me know if additional details are needed or if there's a workaround for this issue.

**Comment by ysolanky** [comment]
Hello @SamuelDevdas!

Thanks for your contribution! The `save_output_to_file` flag is indeed intended to save the last message from the Assistant. However, I see the value in introducing a new parameter, `save_chat_to_file`, that would save the entire conversation. This would be a great addition to the functionality.

Would you be interested in working on this and creating a new PR? Let me know if you'd like to take this on!

**Comment by SamuelDevdas** [comment]
Sure, makes sense. I can add the new input param as suggested and update my pull request.

Could you please review the pull request #1101 and let me know if that works for you? , then I can add the new input parameter as well.
