### ISSUE TITLE
Add `output_model_using_tool` for Assiatant

### ISSUE THREAD

**Issue by KevinZhang19870314** [phidatahq/phidata#1102]
For example, the `startTime` and `endTime` need to use the PythonTools to get the result, so we can defined two models, one `TradesAPIParameter` just with two fields `page` and `size`, another model `TradesAPIParameterWithTool` with also two fields `startTime` and `endTime`. Then we can pass `TradesAPIParameter` to output_model, and `TradesAPIParameterWithTool` to output_model_using_tool. 

For doing this because of the tokens usage, so I guess we can split models according to tools using or not, then we can organize the prompt w/o tools per model, thus we can decrease the tokens usage. For current, I found that each tool run will present all the json_fields in the model as prompt to llm, its waste of tokens. So add one more param `output_model_using_tool` for Assiatant maybe can resolve it I think.

What do you think?

```python
import os
import pathlib

from phi.assistant import Assistant
from phi.llm.openai import OpenAIChat
from phi.tools.python import PythonTools
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()

STORAGE_ROOT = os.getenv('STORAGE_ROOT')
PYTHON_TOOLS_STORAGE = os.getenv('PYTHON_TOOLS')
PYTHON_TOOLS_STORAGE_FOLDER_PATH = os.path.join(STORAGE_ROOT, PYTHON_TOOLS_STORAGE)


class TradesAPIParameter(BaseModel):
	startTime: str = Field(None, description="Start time for transaction creation. Use the python_tools tool to generate the code and get the value, in the format '2024-07-26T00:00:00+08:00'.")
	endTime: str = Field(None, description="End time for transaction creation. Use the python_tools tool to generate the code and get the value, in the format '2024-07-26T23:59:59+08:00'.")
	page: int = Field(1, description="Current page number for pagination.")
	size: int = Field(10, description="Number of records per page for pagination.")


movie_assistant = Assistant(
	llm=OpenAIChat(model="gpt-4o"),
	description="You are a parameter parser for the transaction record query API, responsible for parsing the natural language input by the user into the parameter fields required by this API.",
	output_model=TradesAPIParameter,
	tools=[PythonTools(base_dir=pathlib.Path(PYTHON_TOOLS_STORAGE_FOLDER_PATH))],
	show_tool_calls=False,
	debug_mode=False,
)

params = movie_assistant.run("Query the records, and make sure 14 records are displayed per page.")
print("=========================")
print(params)
print("=========================")
```

**Comment by ysolanky** [comment]
Hello @KevinZhang19870314! This could be a really good addition to Assistant class. I have added this to our feature requests. Please join us on Discord for updates: https://discord.gg/B4uynwPJ
