### ISSUE TITLE
Looking for a Knowledge Base System, that can categorize/summerize/use 1000 pdf/txt and more

### ISSUE THREAD

**Issue by MaximPro** [phidatahq/phidata#1115]
Looking for a Knowledge Base System, that can categorize/summerize/use 1000 pdf/txt and more

I want it, so I can just ask for example my 1000 books on a specific topic. Preferably local.

How could this be done with phidata?

or are there other tools?

Let me know.

ps: I also want to build a product.

**Comment by jacobweiss2305** [comment]
My prefered stack is phidata + pinecone + llama index.

Llama Index for parsing and reading files to vector database.

Phidata Assistant to preform rag on the vector database.

**Comment by jacobweiss2305** [comment]
Give us a shout on discord if you need help setting this help:
https://discord.com/invite/4MtYHHrgA8
