### ISSUE TITLE
Add “--strip-extras” to scripts/upgrade.sh

### ISSUE THREAD

**Issue by mraad** [phidatahq/phidata#112]
Just a warning - but adding --strip-extras removes warning message when running scripts/upgrade.sh

pip-compile --upgrade --no-annotate **--strip-extras** --pip-args "--no-cache-dir" \

**Comment by ashpreetbedi** [comment]
thanks @mraad :) going to update the scripts this week. Probably just thinking of using `uv` now

**Comment by ysolanky** [comment]
Thanks for raising this issue @mraad ! This change was implemented :)
