### ISSUE TITLE
Hybrid search with LanceDB gives error

### ISSUE THREAD

**Issue by Riezebos** [phidatahq/phidata#1189]
I was trying out hybrid search with LanceDB and get an error. I believe this line is causing the error: https://github.com/phidatahq/phidata/blob/main/phi/vectordb/lancedb/lancedb.py#L181
The LanceDB docs show a different way of doing hybrid search when manually giving the vector: https://lancedb.github.io/lancedb/hybrid_search/hybrid_search/#hybrid-search-in-lancedb

Locally I can get it to work if I change that part to:

```python
        results = self.connection.search(
            vector_column_name=self._vector_col,
            query_type="hybrid",
        ).vector(query_embedding).text(query).limit(limit)
```

Is this just me? Or maybe something changed on the LanceDB side?

If it is indeed a bug and my solution looks ok to you, then I am happy to create a PR.

**Comment by jacobweiss2305** [comment]
I was able to replicate, and will fix in release/2.5.0 which is coming next week
