### ISSUE TITLE
Google Gemini support 

### ISSUE THREAD

**Issue by Balogunolalere** [phidatahq/phidata#120]
Please  add Google Gemini support

**Comment by ashpreetbedi** [comment]
Working on it :)

**Comment by ashpreetbedi** [comment]
@Balogunolalere Gemini in the works in this PR: https://github.com/phidatahq/phidata/pull/124

**Comment by ashpreetbedi** [comment]
@Balogunolalere gemini is now available. Here's the cookbook: https://github.com/phidatahq/phidata/tree/main/cookbook/gemini
