### ISSUE TITLE
Allow the assistant to set before and after parameters for Google search lookups based on instruction...in the tools

### ISSUE THREAD

**Issue by mjoe67886** [phidatahq/phidata#1249]
Dear Phidata Team,

I would like to request a feature that allows dynamic setting of "before" and "after" context parameters in tool functions, specifically for internet lookup functions. This would significantly improve the assistant's ability to disambiguate between old and new practices, especially when dealing with version changes in frameworks like Blender. Such a feature could allow users to provide contextually relevant information dynamically, enabling more precise internet lookups and minimizing outdated or irrelevant results. I believe this enhancement could make PHIDATA even more robust and adaptable to real-world, evolving environments.

Thank you for considering this request.

Best regards,

**Comment by jacobweiss2305** [comment]
Nice i like it. Can you give me a psuedo code example

**Comment by mjoe67886** [comment]
Summary: For my Blender script generator with automatic error fixing, I need the PHIDATA assistant to perform Google lookups that take into account the changes in Blender's API between different versions. Specifically, I want it to search for answers that are relevant after Blender 4.2's release and potentially earlier versions like 3.6 or 4.0, based on Blender’s change logs. This helps ensure that the adjustments my generator makes are accurate and suitable for the version in question. I plan on giving the assistant the ability to decide the before and after Parameters based upon a lookup of the consolidated file i'll create of blender change logs from version 2.8 to current and then I'll just workout some logic in order to get it to decide the before and after dates when I do that. For instance I'd like it to have as much information available from an Internet lookup as possible so if it does look up code from when blender 2.8 was released i'd like it to know a full list of all the things that are different from blender 2.8 to blender 4.2 so if I compile list of all the change logs and then whenever my assistant does an Internet lookup have a file assistant look up at a compiled list that I provide on a case by case basis of all the changes from you know blender 2.8 to 4.2 and then maybe if that search doesn't work I'll try it again and say OK here's a list of all the changes from blender 3.6 to blender 4.2, This time of list of just those changes, and blender 4.2 was released on this date and blender 3.6 was released on this date so only look up the Internet for this time. Keeping in mind that you know these are all the changes from blender 3.6 to 4.2.... And then I would provide them by vector file.... If that doesn't make complete sense I'll go into more detail....Didn't include pseudo code because essentially the pseudo code would mirror the logic here but when I write the functionality i'll go ahead and send it if you would implement it I could get started testing it basically you know the assistant you know would just have to respond to the phrase for instance 'blender 4.2 was just released look up on the Internet find out it was released and then help me find fix for this blender python function by only looking up code after that date' I think you should make this because it's important for any API for instance open AI is constantly making changes and you know every single time I ask Chat GPT to look up like even your API for instance I always say look at you know the very latest version of the API and if it looks up fixes on the Internet I don't know how chat GPT designs theirs but it definitely seems logical to look up fixes that are very recent and also integrate the access to any change logs I would provide that in your code intrinsically you know like automatic api lookup if it's requested to generate code and also integrate logic for the looking up of change logs if you want pseudo code on that I'll send it when I do it or just rely on the fact that you may do it I don't know if you need ideas on this... But I'm happy to help make your library Even better than the genius thing I noticed it is....

But if you do want pseudocode just please highlight the logic that's not clear and then I could just work it out, And send my ideas.

**Comment by jacobweiss2305** [comment]
Got it. Let me stew on this. Great use case btw
