### ISSUE TITLE
In this PDF, the LLM Should Provide the Correct Route

### ISSUE THREAD

**Issue by abishekbenjaminraj** [phidatahq/phidata#1250]
I have many Route Map PDFs like the one I uploaded, and I will ask questions about particular routes and how to get to certain routes. The LLM should fetch the correct route from the PDF. Is this possible with Phidata? If so, please provide the solution.

[14.pdf](https://github.com/user-attachments/files/17372584/14.pdf)
[825.pdf](https://github.com/user-attachments/files/17372585/825.pdf)
[FOLDED-System-map-Outside-April-2019.pdf](https://github.com/user-attachments/files/17372588/FOLDED-System-map-Outside-April-2019.pdf)

**Comment by jacobweiss2305** [comment]
I almost think you should store this as .png file then pass them through two models:
openai clip vision model for image embeddings
pass them through the multimodel model as .png for a very detailed description of the image. That description then gets store in vector database as embeddings.
https://github.com/phidatahq/phidata/tree/main/cookbook/advanced_rag/image_search

You asked this on the discord. Let us know how it works or where we can help.
