### ISSUE TITLE
Duplicates comming from the same document list are not filtered

### ISSUE THREAD

**Issue by Tesla2000** [phidatahq/phidata#1255]

**Comment by Tesla2000** [comment]
If 2 documents in document_list have ideantical contents they both get added to the database because thet are not present in DB yet when self.vector_db.doc_exists(document) filter is applied. Added additional filter to fix that https://github.com/phidatahq/phidata/pull/1256

**Comment by jacobweiss2305** [comment]
Good pr thanks @Tesla2000
