### ISSUE TITLE
How to execute multiple tools in series

### ISSUE THREAD

**Issue by ZQFORWARD** [phidatahq/phidata#1257]
I need to build an agent that executes the analysis process. Now I have built multiple analysis tools, such as data acquisition, data preprocessing, data analysis, etc. How to make the Agent execute correctly when some tools' inputs come from the output of another tool? During the process, I found that there were errors in passing parameters to the calling tool and issues with multiple calls.

**Comment by jacobweiss2305** [comment]
@ZQFORWARD There are two things you can do here. Some model providers allow you to do parallel function calling. In the cases where you need parallel function calling use OpenAI. In cases where there are dependent tasks you can either setup a team of agents, or explicity create the chain in .py.

```
step_1: RunResponse = agent.run()

step_2 = agent.run(step_1.content)

```

We are discord come chat with us about this:
https://discord.gg/Az7CvzHb
