### ISSUE TITLE
Feature Request - Sign up to https://www.phidata.app/ with email address

### ISSUE THREAD

**Issue by mobile-appz** [phidatahq/phidata#1259]
It would be preferable to sign up to https://www.phidata.app/ with an email adress rather than using a github or google account

**Comment by ashpreetbedi** [comment]
@mobile-appz good one! we did have a sign-up with email but took it down because we didnt have time to build the forgot-password flow 😂 

give us a few weeks to bring it back

**Comment by mobile-appz** [comment]
Any updates on this please
