### ISSUE TITLE
Assistant's save_and_run, run_files, and run_code functionalities not working

### ISSUE THREAD

**Issue by Balogunolalere** [phidatahq/phidata#126]
**Describe the bug**
The `save_and_run`, `run_files`, and `run_code` functionalities of the Assistant class in the `phi.assistant` module are not working as expected. When these options are set to `True`, the Assistant does not execute the code or save the changes.

**To Reproduce**
1. Create an instance of the Assistant class with `save_and_run=True`, `run_files=True`, and `run_code=True`.
2. Use the `print_response` method to generate some code.
3. Observe that the code is not executed and the changes are not saved.

**Expected behavior**
When `save_and_run`, `run_files`, and `run_code` are set to `True`, the Assistant should execute the generated code and save any changes made to the files.

**Comment by Balogunolalere** [comment]
Tried with both. Please attach a basic example to test with

**Comment by ashpreetbedi** [comment]
Here's a video running the `PythonAssistant` from this [cookbook](https://github.com/phidatahq/phidata/blob/main/cookbook/assistant/python_assistant.py).

https://github.com/phidatahq/phidata/assets/22579644/133e9c2c-a524-47c6-884e-afdcd423e851

Code:
```
from phi.assistant.python import PythonAssistant
from phi.file.local.csv import CsvFile

python_assistant = PythonAssistant(
    files=[
        CsvFile(
            path="https://phidata-public.s3.amazonaws.com/demo_data/IMDB-Movie-Data.csv",
            description="Contains information about movies from IMDB.",
        )
    ],
    pip_install=True,
    show_tool_calls=True,
    run_code=True,
)

python_assistant.print_response("What is the average rating of movies?", markdown=True)
```

**Comment by ashpreetbedi** [comment]
@Balogunolalere is this fixed?

**Comment by Balogunolalere** [comment]
![image](https://github.com/phidatahq/phidata/assets/38155412/5cc6990c-2f69-4b0f-b6dd-21fde7a84034)
didn't work, not sure if it's because i am using ollama instead of openai

**Comment by Balogunolalere** [comment]
![image](https://github.com/phidatahq/phidata/assets/38155412/8601879c-583b-44a5-b35f-fb776aed1253)

**Comment by ashpreetbedi** [comment]
hmm @Balogunolalere please can you show me the code you're running?

**Comment by ashpreetbedi** [comment]
Also @Balogunolalere good to just test with GPT4 to see if this is a code error or model error, a lot of times the local models aren't good enough

**Comment by Balogunolalere** [comment]
> hmm @Balogunolalere please can you show me the code you're running?

![image](https://github.com/phidatahq/phidata/assets/38155412/62398ebf-1ce7-425a-a70e-4352acd4a951)

**Comment by ashpreetbedi** [comment]
@Balogunolalere please can you use `openhermes`, this might just be too difficult for mistral/local models.

Give GPT4 a try, it'll work as expected :) 
Here's the code if needed: https://github.com/phidatahq/phidata/blob/main/cookbook/assistant/python_assistant.py

**Comment by ashpreetbedi** [comment]
@Balogunolalere please test with gpt4 and let me know :) in the meanwhile closing the issue which you can open if it still doesnt work
