### ISSUE TITLE
Tools not working with Ollama local models 

### ISSUE THREAD

**Issue by mobile-appz** [phidatahq/phidata#1260]
The Web Search Agent example doesn't work with Ollama local models.

Code used, incidentally, I also had to add the host parameter in the Ollama inititialisation to get this to work:

"""Run `pip install openai duckduckgo-search` to install dependencies."""

from phi.agent import Agent
from phi.model.ollama import Ollama
from phi.tools.duckduckgo import DuckDuckGo

web_agent = Agent(
    name="Web Agent",
    role="Search the web for information",
    model=Ollama(id="llama3.2",host="[local ollama host and port]"),
    tools=[DuckDuckGo()],
    markdown=True,
    show_tool_calls=True,
)
web_agent.print_response("Whats happening in France?", stream=True)

Error:
Exception has occurred: TypeError
Client.chat() got an unexpected keyword argument 'tools'
  File "[path to phidata]/phidata/cookbook/agents/web_search.py", line 15, in <module>
    web_agent.print_response("Whats happening in France?", stream=True)
TypeError: Client.chat() got an unexpected keyword argument 'tools'

**Comment by ashpreetbedi** [comment]
@mobile-appz thank you, testing

**Comment by ashpreetbedi** [comment]
@mobile-appz you need the new version of ollama python package

please run `pip install -U ollama`

**Comment by ashpreetbedi** [comment]
![CleanShot 2024-10-17 at 11 28 15](https://github.com/user-attachments/assets/401ec836-b74b-4ec5-a210-71dbb33d0956)
