### ISSUE TITLE
CORS issue in the playground

### ISSUE THREAD

**Issue by hemanth** [phidatahq/phidata#1270]
<img width="735" alt="image" src="https://github.com/user-attachments/assets/e8bc7ca4-816a-4097-aac6-ec4e2c14c848">

<img width="326" alt="image" src="https://github.com/user-attachments/assets/c39da72d-a4aa-4b24-83da-88a9eccca570">

This for the demo agent in the [playground](https://www.phidata.app/playground?endpoint=api.demo-agents.com).

**Comment by ashpreetbedi** [comment]
checking i think server overload

**Comment by ashpreetbedi** [comment]
should be fixed now @hemanth please check

**Comment by manthanguptaa** [comment]
hey @hemanth, are you still facing this issue?

**Comment by hemanth** [comment]
@manthanguptaa No more CORS errors, but the response isn't as complete. 

<img width="889" alt="image" src="https://github.com/user-attachments/assets/b3bd1d55-5009-43de-9974-ce3541b26c3d">
