### ISSUE TITLE
PythonAssistant - ERROR: Function multi_tool_use.parallel not found  

### ISSUE THREAD

**Issue by jacobweiss2305** [phidatahq/phidata#128]
## Issue

- Python Assistant will not pip install packages

- pip_install=True, is causing an error "ERROR: Function multi_tool_use.parallel not found"

- pip_install=False the code runs without error.

## Phidata Version
2.3.36

## Code
``` python
from phi.assistant.python import PythonAssistant
from phi.file.local.csv import CsvFile
from rich.pretty import pprint
from pydantic import BaseModel, Field


class AssistantResponse(BaseModel):
    result: str = Field(..., description="The result of the users question.")


def average_rating() -> AssistantResponse:
    python_assistant = PythonAssistant(
        files=[
            CsvFile(
                path="https://phidata-public.s3.amazonaws.com/demo_data/IMDB-Movie-Data.csv",
                description="Contains information about movies from IMDB.",
            )
        ],
        instructions=[
            "Only provide the result, do not need to provide any additional information.",
        ],
        # This will make sure the output is of this Assistant is an object of the `AssistantResponse` class
        output_model=AssistantResponse,
        # This will allow the Assistant to directly run python code, risky but fun
        run_code=True,
        # Uncomment the following line to let the assistant install python packages
        pip_install=True,
        # Uncomment the following line to show debug logs
        # debug_mode=True,
    )

    response: AssistantResponse = python_assistant.run("What is the average rating of movies?")  # type: ignore
    return response
```

## Requirements
Package            Version
------------------ --------
annotated-types    0.6.0
anyio              4.3.0
asttokens          2.4.1
boto3              1.34.50
botocore           1.34.50
certifi            2024.2.2
charset-normalizer 3.3.2
click              8.1.7
colorama           0.4.6
comm               0.2.1
debugpy            1.8.1
decorator          5.1.1
distro             1.9.0
docker             7.0.0
executing          2.0.1
gitdb              4.0.11
GitPython          3.1.42
h11                0.14.0
httpcore           1.0.4
httpx              0.27.0
idna               3.6
ipykernel          6.29.3
ipython            8.22.1
jedi               0.19.1
jmespath           1.0.1
jupyter_client     8.6.0
jupyter_core       5.7.1
markdown-it-py     3.0.0
matplotlib-inline  0.1.6
mdurl              0.1.2
nest-asyncio       1.6.0
numpy              1.26.4
openai             1.12.0
packaging          23.2
pandas             2.2.1
parso              0.8.3
phidata            2.3.43
pip                22.3.1
platformdirs       4.2.0
prompt-toolkit     3.0.43
psutil             5.9.8
pure-eval          0.2.2
pydantic           2.6.2
pydantic_core      2.16.3
pydantic-settings  2.2.1
Pygments           2.17.2
python-dateutil    2.8.2
python-dotenv      1.0.1
pytz               2024.1
pywin32            306
PyYAML             6.0.1
pyzmq              25.1.2
requests           2.31.0
rich               13.7.0
s3transfer         0.10.0
setuptools         65.5.0
six                1.16.0
smmap              5.0.1
sniffio            1.3.1
stack-data         0.6.3
tomli              2.0.1
tornado            6.4
tqdm               4.66.2
traitlets          5.14.1
typer              0.9.0
typing_extensions  4.10.0
tzdata             2024.1
urllib3            2.0.7
wcwidth            0.2.13

**Comment by ashpreetbedi** [comment]
@jacobweiss2305 sorry this is a transient error from GPT4 sadly. It tries to call the tool `multi_tool_use.parallel` which is an internal function and not a function we provide. 

Not much we can fix but I'll add automatic retries to ensure better error handing

**Comment by jacobweiss2305** [comment]
Thanks @ashpreetbedi
