### ISSUE TITLE
agent builder team

### ISSUE THREAD

**Issue by mayphilc** [phidatahq/phidata#1295]
would it be possible to create a starter team that can scrape websites for research, vectorize the data for rag and have the ability to write teams and agents and tools? surely there has to be a way to load teams and tools modularly, we already have the cookbook so phidata knows iteself already basically it wouldnt be a far fetch to add python support. either it could give full new teams and agents or better yet sideload them

**Comment by Skatingdragon** [comment]
Is that you tried this?? So we have some stranded agents, right? We cannot customize them, right?

**Comment by mayphilc** [comment]
> Is that you tried this?? So we have some stranded agents, right? We cannot customize them, right?

sorry, i only speak english..

**Comment by Skatingdragon** [comment]
> > Is that you tried this?? So we have some stranded agents, right? We cannot customize them, right?
> 
> sorry, i only speak english..
> 
> 
> 
> 

Sorry, I don't know that you're a bot.

**Comment by mayphilc** [comment]
> > > Is that you tried this?? So we have some stranded agents, right? We cannot customize them, right?
> > 
> > 
> > sorry, i only speak english..
> 
> Sorry, I don't know that you're a bot.

Go back to China 🇨🇳
