### ISSUE TITLE
agent: DDG + Ollama

### ISSUE THREAD

**Issue by hemanth** [phidatahq/phidata#1296]
<img width="1391" alt="image" src="https://github.com/user-attachments/assets/bd409846-3843-432c-964e-09797e5a3504">

What am I missing? The `web_agent` is not able to fetch the right info from `DDG` but the `duckduckgo-search` package can.

**Comment by ysolanky** [comment]
@hemanth sorry, can you please set `debug_mode=True` in the Agent config and share the logs? Curious to see what happened
