### ISSUE TITLE
🪛 Optimization in the playground.py Agent definition

### ISSUE THREAD

**Issue by 6rz6** [phidatahq/phidata#1297]
Not sure i understand why is it necessary to redefine the agents class in the playground file while they are already fully defined under the python phidata/cookbook/agents folder unless i would like to override a property.

wouldn't it be simpler to be able to just define the class based on the agent file where all the properties are predefined in an agent file and just call it by passing the agent name or the file name?

finance_agent = Agent(

#pass finance_agent or finance_agent.py to a func property
    func="finance_agent.py", 

#override only the model and pass the rest of the properties defined in finance_agent.py 
    model=OpenAIChat(id="gpt-4o-mini")  
)

app = Playground(agents=[finance_agent]).get_app()

**Comment by manthanguptaa** [comment]
Hey @6rz6, each file in the Python cookbook is a standalone example for everyone to try out. We wanted the code to be easily accessible to everyone instead of losing on readability. Though your point is valid and I agree to it. It should look something like this 

```
def get_finance_agent() -> Agent:
    return Agent(
        name="Finance Agent",
        agent_id="finance-agent",
        model=OpenAIChat(model="gpt-4o"),
        tools=[YFinanceTools(enable_all_tools=True)],
        description="You are a finance agent",
        markdown=True,
        show_tool_calls=True,
    )
    
finance_agent = get_finance_agent(debug_mode=True)

# Create a playground instance
playground = Playground(agents=[finance_agent])
```
