### ISSUE TITLE
Took a long time to build PDFKnowledgeBase

### ISSUE THREAD

**Issue by scottyeung** [phidatahq/phidata#1299]
Hi there,

It took a long time to load the PDF like for 150 pages and for creating embeddings.
How can I use async to get the status of the PDFKnowledge to know whether it's building or not?

**Comment by ysolanky** [comment]
Hey @scottyeung ! Unfortunately currently insert function of phidata vectordb classes works synchronously. Though I think it's an excellent suggestion to support async insert as well. I believe Qdrant and Pinecone offer this out of the box. I am going to add this to our feature requests. Thank you!
