### ISSUE TITLE
Feature Request 「plz support InternLM2.5」

### ISSUE THREAD

**Issue by boshallen** [phidatahq/phidata#1306]
Hi,

I noticed that the repository currently lacks support for the InternLM2.5-7B (1.8B, 20B) model, which may cause compatibility issues or missing steps for users trying to implement it. It would be beneficial to update the repository with detailed instructions or tools for integrating and using the InternLM2.5-7B model, ensuring the content remains relevant.

I believe that adding this support would significantly enhance the usability of the project. While some manual adjustments are possible, official guidance or toolchain support would be much more efficient and advantageous, especially for new users.

If possible, including example scripts or demonstrating integration with InternLM2.5-7B would also be a valuable addition.

For further support, please add the InternLM Assistant (WeChat search: InternLM) or join the InternLM Discord(https://discord.com/invite/xa29JuW87d).

**Comment by manthanguptaa** [comment]
Hi @boshallen ,

Thank you for bringing this up and for your valuable suggestion! I completely agree that adding support for the InternLM2.5-7B (1.8B, 20B) models would be a great enhancement. I'm happy to share that this is on the roadmap.

We are actively working on integrating support for these models into the repository, along with detailed instructions, example scripts, and tools to make the process as smooth as possible for all users, especially those new to the project.

Please stay tuned for upcoming updates, and don't hesitate to reach out if you have any more questions or feedback in the meantime.
