### ISSUE TITLE
Documentation addition to docker.sock errors for MacOS / Docker Desktop

### ISSUE THREAD

**Issue by mcauthorn** [phidatahq/phidata#1313]
Hi there, I ran into the `docker.sock` error today and wanted to share a simple solution with you for your users on MacOS. Running Docker desktop, go to settings -> advanced. Then enable "allow default Docker socket to be used" :

<img width="899" alt="image" src="https://github.com/user-attachments/assets/6bef4560-d16c-4574-b90c-a90a59e219b1">

Enabling this immediately resolves the issue, without a need for symlinks or permissions changes. 

Great project, looking forward to digging in more!

**Comment by ashpreetbedi** [comment]
This is amazing! thank you @mcauthorn

This is such an annoying docker issue at times

**Comment by ashpreetbedi** [comment]
I appreciate this so much cannot explain 🤩

**Comment by mcauthorn** [comment]
Loving the project so far, so it's the least I can do!
