### ISSUE TITLE
can you add voice recog and support auto response?

### ISSUE THREAD

**Issue by thanhauco** [phidatahq/phidata#1318]

**Comment by manthanguptaa** [comment]
Hey @thanhauco, voice recognition sounds like a really good addition. Do you mind adding a description to the issue? Would love to know more about auto-response. Also, do you want both of these features in Agent UI?

**Comment by thanhauco** [comment]
Thank you for response. Imagine you have a chatbot support voice in conversation, helpful for accessibility and user can use tablet to code via voice for quick. It is also helpful for teachers to plan via local documents by talking instead of typing a lot back and forth. The chatbot must understand the text in questions via live conversation and give fast response accordingly. If you can add this feature, it'd be great product.
