### ISSUE TITLE
Add Weaviate VectorDb

### ISSUE THREAD

**Issue by ysolanky** [phidatahq/phidata#1324]
Add Weaviate as a VectorDb

- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [Weaviate Docs](https://weaviate.io/developers/weaviate/client-libraries/python)

**Comment by rohinish404** [comment]
@ysolanky can i take this issue up?

**Comment by ysolanky** [comment]
Yes of course @rohinish404! Do let me know if you have any questions. Looking forward to reviewing the PR 🙌

**Comment by rohinish404** [comment]
> Yes of course @rohinish404! Do let me know if you have any questions. Looking forward to reviewing the PR 🙌

Can i create a draft pr first with some functions i had written up until now?

**Comment by manthanguptaa** [comment]
Hey @rohinish404! Go for it

**Comment by rohinish404** [comment]
I'm facing some issues while implementing the insert function.

**Comment by manthanguptaa** [comment]
Hey @rohinish404, are you still facing this issue?

**Comment by Aryann15** [comment]
Hey @manthanguptaa  @ysolanky 👋. Can I have a try at this as well?

**Comment by manthanguptaa** [comment]
Hey @Aryann15, thanks for showing interest in contributing to Phidata. This issue is already assigned and a PR is already up for the same. You can take a look at the other issues or find something new to work on

**Comment by rohinish404** [comment]
> Hey @rohinish404, are you still facing this issue?

i have mentioned you in pr with some doubts.

**Comment by manthanguptaa** [comment]
Hey @rohinish404, are you still working on this issue?

**Comment by rohinish404** [comment]
> Hey @rohinish404, are you still working on this issue?

Hey @manthanguptaa , i won't be able to give time to this issue. Sorry for late reply. You can assign someone else. Thanks!

**Comment by ima-helikoptaaa** [comment]
Hey Manthan, can I be assigned this issue?

**Comment by manthanguptaa** [comment]
Sure @ima-helikoptaaa! Assigning you right away

**Comment by manthanguptaa** [comment]
Hey @ima-helikoptaaa, you still working on this?
