### ISSUE TITLE
Add Redis as a VectorDB 

### ISSUE THREAD

**Issue by manthanguptaa** [phidatahq/phidata#1325]
- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [Redis Doc](https://redis.io/docs/latest/develop/get-started/vector-database/)

**Comment by Player256** [comment]
@manthanguptaa I think i'd to like to give this a try

**Comment by manthanguptaa** [comment]
Hey @Player256, thanks for showing interest in contributing to Phidata. This is an interesting issue to pick up. I am assigning this to you. I look forward to your PR

**Comment by Player256** [comment]
@manthanguptaa sorry for the delayed pr. I would love some feedback on the draft pr and direction where it should be going.

**Comment by gnanesh-16** [comment]
Hey, @manthanguptaa. I  noticed that the integration of Redis as a VectorDB (#1325) is currently being assigned. I would love to contribute to this project and have drafted my pull request for your review.

**Comment by manthanguptaa** [comment]
Hey @gnanesh-16, this issue is already assigned to @Player256, and has already raised a PR for the same. I will be reviewing all the PRs from Monday. I will have to sadly close your open PR.

**Comment by gnanesh-16** [comment]
Okay, @manthanguptaa no problem!
