### ISSUE TITLE
Add Clickhouse as a VectorDB

### ISSUE THREAD

**Issue by manthanguptaa** [phidatahq/phidata#1326]
- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [Clickhouse Doc](https://clickhouse.com/blog/vector-search-clickhouse-p1)

**Comment by rajnsunny** [comment]
I would love to work on this. Can you assign me ? @manthanguptaa .

**Comment by manthanguptaa** [comment]
Hey @rajnsunny, thanks for showing interest in contributing to Phidata. I look forward to seeing your PR.

**Comment by manthanguptaa** [comment]
Hey @rajnsunny, are you still working on this?

**Comment by vodkar** [comment]
I would like to implement ClickHouse integration, in case of missing response from @rajnsunny.

**Comment by manthanguptaa** [comment]
sure @vodkar, go ahead

**Comment by manthanguptaa** [comment]
Hey @vodkar, are you still working on this issue?

**Comment by vodkar** [comment]
> Hey @vodkar, are you still working on this issue?

Yep, I can create a PR if you want to track my progress

**Comment by vodkar** [comment]
Btw, PR is ready for review: https://github.com/phidatahq/phidata/pull/1503

I would like to test it more than example from cookbook. 
Can you help me with some special testcases? @manthanguptaa

**Comment by manthanguptaa** [comment]
Hey @vodkar, you can try different RAGs with your examples to test it out. 
https://github.com/phidatahq/phidata/tree/main/cookbook/rag
