### ISSUE TITLE
Add Elasticsearch as a VectorDB

### ISSUE THREAD

**Issue by manthanguptaa** [phidatahq/phidata#1327]
- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [Elasticsearch Doc](https://www.elastic.co/elasticsearch/vector-database)

**Comment by pritipsingh** [comment]
Hi @manthanguptaa , can i please take this up ?

**Comment by manthanguptaa** [comment]
Hey @pritipsingh, go for it!

**Comment by nitin5599** [comment]
Hey @manthanguptaa , Is anyone working on this? if not, I can look into this issue. Let me know!

**Comment by manthanguptaa** [comment]
Hey @nitin5599, thanks for showing interest in contributing to Phidata. You can take a go at it. I look forward to your PR

**Comment by manthanguptaa** [comment]
Hey @nitin5599, are you still working on this?
