### ISSUE TITLE
Add Cassandra as a VectorDB

### ISSUE THREAD

**Issue by manthanguptaa** [phidatahq/phidata#1328]
- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [Cassandra Doc](https://cassandra.apache.org/doc/latest/cassandra/getting-started/vector-search-quickstart.html)

**Comment by VedantS20** [comment]
I would Like to work on this feature @manthanguptaa

**Comment by manthanguptaa** [comment]
Hey @VedantS20, are you still working on this?

**Comment by VedantS20** [comment]
Yes @manthanguptaa , it's almost done. I'll raise the PR in the next 2 days.

**Comment by manthanguptaa** [comment]
Take your time @VedantS20. I just wanted to confirm if you are still working on this

**Comment by VedantS20** [comment]
@manthanguptaa Sorry for the delay, I have created the PR. please check.
