### ISSUE TITLE
Add MongoDB as a VectorDB

### ISSUE THREAD

**Issue by manthanguptaa** [phidatahq/phidata#1329]
- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [MongoDB Doc](https://www.mongodb.com/docs/atlas/atlas-vector-search/tutorials/vector-search-quick-start/)

**Comment by STSonyThomas** [comment]
Hey I would like to work on this can you assign this issue to me?

**Comment by manthanguptaa** [comment]
Hey @STSonyThomas, thanks for showing interest in contributing to Phidata. I am assigning this issue to you. I look forward to your PR!
