### ISSUE TITLE
Add Linear as a tool

### ISSUE THREAD

**Issue by manthanguptaa** [phidatahq/phidata#1331]
- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [Linear Doc](https://developers.linear.app/docs)

**Comment by vishkrish200** [comment]
hey @manthanguptaa, i would like to work on this issue as well, but if i am issue hogging then happy to work on a different one :)

**Comment by manthanguptaa** [comment]
Hey @vishkrish200, let's first get your discord PR merged and then you can work on this. Give me some time to review that

**Comment by dundermain** [comment]
Hey @manthanguptaa, if no one is working on this issue, could you please assign this to me?

**Comment by manthanguptaa** [comment]
Hey @dundermain, thanks for your interest in contributing to Phidata. I am assigning this issue to you. I look forward to your PR
