### ISSUE TITLE
Add Google Calendar as a tool

### ISSUE THREAD

**Issue by manthanguptaa** [phidatahq/phidata#1332]
- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [Google Calendar Doc](https://developers.google.com/calendar/api/quickstart/python)

**Comment by manthanguptaa** [comment]
Hey @Ankitmohanty2! Thank you for showing interest in contributing to Phidata. I am assigning this issue to you. Let me know if you have any questions.

**Comment by vishkrish200** [comment]
hey @manthanguptaa can i finish up this issue?

**Comment by manthanguptaa** [comment]
Hey @Ankitmohanty2, are you still working on this?

**Comment by Ankitmohanty2** [comment]
I tried but not completed

**Comment by manthanguptaa** [comment]
Do you want some help @Ankitmohanty2?

**Comment by Ankitmohanty2** [comment]
I attempted to implement the requested changes, but I encountered some challenges and couldn't get it working as expected.

**Comment by manthanguptaa** [comment]
what's the challenge you are facing? Maybe I can help you

**Comment by VedantS20** [comment]
Hey @manthanguptaa, Can I work on this? I recently raised my PR for a Vector Db, and I would love to give this a try as well.

**Comment by manthanguptaa** [comment]
Sure @VedantS20, go for it!

**Comment by manthanguptaa** [comment]
Hey @VedantS20, are you still working on this issue?

**Comment by VedantS20** [comment]
Yes @manthanguptaa I'm working on this. i'll finish over this weekend
