### ISSUE TITLE
Add Confluence as a tool

### ISSUE THREAD

**Issue by manthanguptaa** [phidatahq/phidata#1333]
- [How to contribute](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md)
- [Confluence Doc](https://atlassian-python-api.readthedocs.io/)

**Comment by STSonyThomas** [comment]
Hey can you assign this issue to me?

**Comment by manthanguptaa** [comment]
Hey @STSonyThomas, thanks for showing interest in contributing to Phidata. I would love to assign this issue to you but let's close #1329 first.

**Comment by STSonyThomas** [comment]
Alright I'll do that.

**Comment by sahildotexe** [comment]
Hey @manthanguptaa , can you assign this issue to me?

**Comment by manthanguptaa** [comment]
Hey @sahildotexe, are you still working on the feedback I provided you on the PR?

**Comment by philip-shinra** [comment]
hy @manthanguptaa  is this issue closed ?

**Comment by manthanguptaa** [comment]
Hey @philip-shinra, it is not. Are you interested in taking this up?

**Comment by philip-shinra** [comment]
yeah sure @manthanguptaa  you can assign it to me.
