### ISSUE TITLE
can we host phidata.app in local?

### ISSUE THREAD

**Issue by senthilkumar-td** [phidatahq/phidata#1338]
Hi, 
Can you please help me to host phidata.app in local? I am struggling to find that app source code in the repo https://github.com/phidatahq

or it is a paid service? Can you please elaborate more on this?

I am able to host sample agents & connect with live app by referring this url : https://github.com/phidatahq/phidata

But I would like to host phidata.app & its entire source code at local for own development. is that feasible? Can you help me on this?

Thanking you.
Senthil

**Comment by manthanguptaa** [comment]
Hey @senthilkumar-td, phidata app isn't open source, and is not feasible to provide you with the source code. Let me know if you need help or have more questions.

**Comment by senthilkumar-td** [comment]
Hi, thanks for answering
