### ISSUE TITLE
Add json format to user message or system prompt

### ISSUE THREAD

**Issue by jacobweiss2305** [phidatahq/phidata#1339]
Discord user would like to add json format to user message instead of system prompt. We would like to give devs the option to do either.

**Comment by nitin5599** [comment]
Hey @jacobweiss2305 If you don't mind, I would like to work on this one.

**Comment by jacobweiss2305** [comment]
@nitin5599  go for it.

Here are some steps to get you started:

Add `response_model_system_prompt: Optional[bool] = True` to Agent class
```
    # -*- Agent Response Settings
    # Provide a response model to get the response as a Pydantic model
    response_model: Optional[Type[BaseModel]] = Field(None, alias="output_model")
    # -*- Agent Response Message Settings
    # If True, add the response_model instructions to the system prompt
    response_model_system_prompt: Optional[bool] = True
   ```
   
   Adjust all the structured output logic in get_system_messsage:
   ```
               if self.response_model is not None and self.structured_outputs is False and self.response_model_system_prompt:
                system_prompt_from_template += f"\n{self.get_json_output_prompt()}"
                
    ```
    
    
    Add logic to get_user_message:
    ```
            if self.response_model is not None and not self.structured_outputs and self.response_model_system_prompt:
            user_prompt += f"\n{self.get_json_output_prompt()}"
     ```
     
     Make sure you have a test script (cookbook\providers\openai\structured_output.py)
     ``` 
     json_mode_agent_no_system_prompt = Agent(
    model=OpenAIChat(id="gpt-4o"),
    description="You write movie scripts.",
    response_model=MovieScript,
    response_model_system_prompt=False,
)
```

You will also need to check how response_model is getting handled here:
phi\model\openai\chat.py

**Comment by nitin5599** [comment]
@jacobweiss2305  Can I get dummy API keys to run sample agents? I was trying to run web_search agent given in README docs but OpenAI api keys I generated do not have access to model gpt-4o.

![image](https://github.com/user-attachments/assets/9c14d667-5274-406c-9aeb-907be10b6b57)
