### ISSUE TITLE
Model classes are not interchangable

### ISSUE THREAD

**Issue by x3419** [phidatahq/phidata#1342]
Hi,
There are certain instances where the models cannot be used interchangeably.
For example, I noticed that you can't use Groq in the AgentUI for some reason.

Currently in my project I was using OpenAI and changed to groq/deepseek and I encountered issues, including the following error when switching to deepseek. The issue may be related to the response format.

`ERROR    Error from OpenAI API: Failed to deserialize the JSON body into the target type: response_format: response_format.type json_schema is           
         unavailable now at line 1 column 3370
`

Thank you

**Comment by ashpreetbedi** [comment]
hey @x3419, the models should be interchangeable but will have to check if certain functionality is missing from groq

Please can you share some code.
