### ISSUE TITLE
Groq Support

### ISSUE THREAD

**Issue by unclecode** [phidatahq/phidata#135]
Do u guys have any plan for integrating w/ Grok? Currently, it seems u depend on OpenAI tools' functionality. Adding a mechanism to detect tools using Grok could bring crazy speed benefits here for a more efficient assistant. Hope u're considering a plan. 🚀

**Comment by ashpreetbedi** [comment]
@unclecode we support Groq, please checkout [this cookbook for an example](https://github.com/phidatahq/phidata/tree/main/cookbook/groq). We're waiting for Groq to support tool calls so as soon as they do we'll have function calling at ⚡ speed!

**Comment by unclecode** [comment]
Thanks for the reply. I actually tried this, and can I use Pydantic output with Groq, or does that also require the ability to make function calls.

**Comment by ashpreetbedi** [comment]
@unclecode sadly not yet. While our pyndatic/structured output doesnt require function calls, it uses JSON mode which is also not yet supported by Groq. If i had to take a guess it's just around the corner as this seems like an important feature for them :)

**Comment by ashpreetbedi** [comment]
@unclecode just saw your twitter post adding a proxy server for function calling. Really, really awesome work!! would love to play around if you're open to sharing the proxy

**Comment by unclecode** [comment]
Hi, yes, I was actually going to share it with you. I really enjoy the beauty of how PhiData is expressive. There is just enough there—not too complicated to accomplish one simple task, and not too little that you can' take it seriously. Really, great job. And yes, I definitely appreciate any form of collaboration. For now, it's a baby version, but I'll try to wrap it up and put it in a repo. I'm all in if I can contribute anything to PhiData; it would be my pleasure.  @ashpreetbedi

**Comment by ashpreetbedi** [comment]
@unclecode thank you for the kind words! 

Please share when the repo is up, would love to play around and collaborate wherever we can. Shall we continue the discussion on [discord](https://discord.com/invite/4MtYHHrgA8)?

**Comment by unclecode** [comment]
Awesome, Just joined to discord, will talk more over there 😎

**Comment by ashpreetbedi** [comment]
see you :)
