### ISSUE TITLE
Add Cal.com as a tool

### ISSUE THREAD

**Issue by jayeshp19** [phidatahq/phidata#1362]
Hello I would like to add Cal.com as a tool, I think it would be helpful for scheduling process via agent.

[Cal docs](https://cal.com/docs/api-reference/v2/introduction)

CC: @manthanguptaa @ysolanky

**Comment by JeetKaria06** [comment]
Hi, I would like to take this issue up and work on it.

Are there any prerequisites for phidata you want me to go through @manthanguptaa @ysolanky regarding new feature implementation, also if there is any pre-defined process I should follow in terms of any doc creation?

**Comment by manthanguptaa** [comment]
Hey @JeetKaria06, thanks for showing interest in contributing to Phidata. This issue has already been assigned to @jayeshp19. You can take up some other issue or find something you want to add to the repository

**Comment by JeetKaria06** [comment]
Okay, no worries, thanks!
