### ISSUE TITLE
Feature Request: Add support for custom chunking strategy for all types of document readers

### ISSUE THREAD

**Issue by yogin16** [phidatahq/phidata#1373]
Inspiration: 5-levels of chunking

[https://github.com/FullStackRetrieval-com/RetrievalTutorials/blob/main/tutorials/LevelsOfTextSplitting/5_Levels_Of_Text_Splitting.ipynb](https://github.com/FullStackRetrieval-com/RetrievalTutorials/blob/main/tutorials/LevelsOfTextSplitting/5_Levels_Of_Text_Splitting.ipynb)

Reader should support multiple levels of chunking strategy, including a custom chunker

**Comment by manthanguptaa** [comment]
That's a great suggestion @yogin16! I will bring this up to the team and see when we can have this feature incorporated. Thank you for this excellent suggestion
