### ISSUE TITLE
DeepSeek not working with Agent

### ISSUE THREAD

**Issue by josephtrinh** [phidatahq/phidata#1374]
I've only recently started exploring Phidata and trying out those DeepSeek agents under cookbook and I'm getting the same error every time. I've tried out the Gemini one and those worked fine for me. I have also tried the Assistant and those worked fine when I modified it for DeepSeek. I'm mainly interested in using DeepSeek at this point. I'm not entirely sure how to get Agent to work with DeepSeek after trying for about an hour with different settings and looking around on google.

`An error occurred: 'CompletionUsage' object has no attribute 'prompt_tokens_details'`

https://github.com/phidatahq/phidata/tree/main/cookbook/providers/deepseek

Assistant
```
from phi.assistant import Assistant
from phi.llm.deepseek import DeepSeekChat
from phi.tools.duckduckgo import DuckDuckGo

assistant = Assistant(
    llm=DeepSeekChat(),
    tools=[DuckDuckGo()],
    show_tool_calls=True,
    markdown=True,
)
assistant.print_response("What is happening with AI today?")
```

**Comment by manthanguptaa** [comment]
Hey @josephtrinh, as you have only started using Phidata recently, I suggest you move to Agent as Assistant will be deprecated in the 3.0.0 version. Here is an example of using deepseek with Agent 

```
"""Run `pip install duckduckgo-search` to install dependencies."""

from phi.agent import Agent
from phi.model.deepseek import DeepSeekChat
from phi.tools.duckduckgo import DuckDuckGo

agent = Agent(
    model=DeepSeekChat(),
    tools=[DuckDuckGo()],
    show_tool_calls=True,
    markdown=True,
)

agent.print_response("Whats happening in France?", stream=True)

```

Let me know if you run into any issues

**Comment by manthanguptaa** [comment]
Can you run `pip install -U phidata` and try again

**Comment by josephtrinh** [comment]
Once I update to 2.5.26 with pip, I'm back to getting the `An error occurred: 'CompletionUsage' object has no attribute 'prompt_tokens_details'` error. I have re-edit the openai/chat.py file to get the Agent to work again.

**Comment by manthanguptaa** [comment]
That shouldn't be the case as it's working perfectly fine for me without any changes. Can you run `pip install -U openai` and then try running?

**Comment by josephtrinh** [comment]
@manthanguptaa appreciate the help. Updating to openai-1.53.0 got the Agent to work. thanks!

`Installing collected packages: openai
  Attempting uninstall: openai
    Found existing installation: openai 1.42.0
    Uninstalling openai-1.42.0:
      Successfully uninstalled openai-1.42.0
Successfully installed openai-1.53.0`

**Comment by manthanguptaa** [comment]
Great to know @josephtrinh! Keep building with phidata
