### ISSUE TITLE
[Feature Request]: Add support for Couchbase Vector Database 

### ISSUE THREAD

**Issue by shivay-couchbase** [phidatahq/phidata#1375]
Couchbase is one of the leading NoSQL database solutions. It added support for [vector search](https://www.couchbase.com/products/vector-search/) earlier this year. I would like to suggest the addition of Couchbase Vector search to the existing list of VectorDBs support for PhiData

**Comment by Himasnhu-AT** [comment]
hi @shivay-couchbase , let me know your though on this, and if possible, perform a review. Haven't use couchbase so unsure if this is the best practise.

**Comment by manthanguptaa** [comment]
Hey @shivay-couchbase, sounds like a very good addition. Would you like to take this up?

**Comment by shivay-couchbase** [comment]
Hey @manthanguptaa yeah I will discuss with my team regarding this integration, and then either I myself, or someone from our integrations team will work on this! Looking forward to this integration!
