### ISSUE TITLE
[New Embedder Request]: Add Qdrant FastEmbed as an Embedder Option

### ISSUE THREAD

**Issue by sashank5644** [phidatahq/phidata#1379]
Qdrant FastEmbed is a lightweight, efficient embedding library optimized for fast inference and limited dependencies. Some if its advantages include: 

1. High-Speed Embedding Generation: (50% faster) than traditional PyTorch-based transformers, making it ideal for real-time applications.
2. Resource Efficiency: With model quantization and ONNX Runtime integration, FastEmbed minimizes memory and CPU use.
3. Enhanced Retrieval with Prefix-Based Embeddings: FastEmbed supports specialized input prefixes like "query" and "Passage" which allows model to generate differentiated embeddings for queries and documents, optimizing retrieval accuracy and semantic search.

I though it might be a great addition to the existing embeddings, and if it seems like a fit, I would love to take this integration task.

**Comment by manthanguptaa** [comment]
Hey @sashank5644, Qdrant FastEmbed sounds like a really good addition. Go for it! I am excited to look at your PR.

**Comment by manthanguptaa** [comment]
Thank you @sashank5644 for the PR! It's merged now.
