### ISSUE TITLE
Add Huggingface as a model provider[FEAT request]

### ISSUE THREAD

**Issue by JINO-ROHIT** [phidatahq/phidata#1380]
Hi, really cool library. I was wondering if HF as a model provider can be supported ?

If its in the roadmap, Id be happy to raise a PR.

lmk

**Comment by manthanguptaa** [comment]
Hey @JINO-ROHIT, go ahead. This will be a great integration to have! I look forward to your PR

**Comment by JINO-ROHIT** [comment]
gotcha, will raise an early draft for review

**Comment by manthanguptaa** [comment]
Hey @JINO-ROHIT, somebody else raised a PR for the same at https://github.com/phidatahq/phidata/pull/1391 and it's merged now. I will have to sadly close your draft now. Thank you for your attempt at this issue!
