### ISSUE TITLE
[Feature Request]: Add support for Milvus Vector Database

### ISSUE THREAD

**Issue by AbhishekRP2002** [phidatahq/phidata#1398]
Milvus is a high-performant, scalable open-source vector database which is adopted by multiple industry leaders ( Salesforce, Nvidia, Walmart to name a few . ref: https://milvus.io/use-cases ) to power up their AI applications.

Since, it's used in enterprise level, so integrating it with `phidata`  can be beneficial for folks working around data augmented llm agentic applications.

Scope:
- Milvus supports 3 deployment modes : Milvus Lite, Milvus Standalone and Milvus Distributed.
- We can start with integrating Milvus Lite, a lightweight version of Milvus via their python client library. Post successful integration of Milvus Lite, we can support `Milvus Standalone and Distributed` since all deployment modes of Milvus share the same API, so the client side code doesn’t need to change much if moving to another deployment mode. 

ref: https://milvus.io/docs/overview.md

cc: @manthanguptaa

**Comment by manthanguptaa** [comment]
go for it @AbhishekRP2002!

**Comment by manthanguptaa** [comment]
Hey @AbhishekRP2002, are you still working on this?

**Comment by AbhishekRP2002** [comment]
Yes. Will raise a PR in a day or two.

**Comment by manthanguptaa** [comment]
Hey @AbhishekRP2002, are you still working on this issue?

**Comment by philip-shinra** [comment]
hy, is this feature added  yet ?

**Comment by manthanguptaa** [comment]
Yes @philip-shinra, it is
