### ISSUE TITLE
Issue: Incorrect Response Handling with `stream=True` in Ollama Deployment

### ISSUE THREAD

**Issue by OverrideTuring** [phidatahq/phidata#1404]
When using the agent, I encountered an issue where the prompt is structured as follows:
```
Text: My name is Jack. I come from America. I'm an associate professor working at the University of California.
Extract specific information about Jack from the provided text above. Answer only in the format: {"name": "", "affiliation": ""}.
For example: {"name": "Mike", "affiliation": "Professor, University of Cambridge, England"}
```
The expected response from the LLM is:
```
{"name": "Jack", "affiliation": "Associate Professor, University of California, America"}
```
However, when I set `stream=True`, the expected response is not received, although it is visible in the command line/terminal. The LLM is deployed using Ollama. Upon debugging `phi.llm.ollama.chat.py`, I discovered that the issue originates in the `response_stream()` function. It incorrectly treats any JSON-format `{}` as an indicator of a tool-call. As a result, the response is suppressed unless `stream=False` is set, which works as expected.

To resolve this, I suggest introducing a parameter to disable the tool-call check or implement a proper fix that correctly handles this case with `stream=True`.

**Comment by ysolanky** [comment]
Hey @OverrideTuring !

That is a good catch. You are right, the `response_stream()` function would incorrectly classify the response from your prompt as a tool call. Unfortunately due to the way Ollama handles tool calls for streaming, we have to check all chunks for `{` which indicates start of a tool call. Let me find a fix for this and get back to you!

Thanks for making phidata better

**Comment by ysolanky** [comment]
@OverrideTuring Ollama just updated their SDK to better support tool call streaming, which now works great with phidata. Please reopen the issue if you face any problems
