### ISSUE TITLE
Add SQLite as VectorDB

### ISSUE THREAD

**Issue by ArchishmanSengupta** [phidatahq/phidata#1411]

**Comment by manthanguptaa** [comment]
Hey @ArchishmanSengupta, great that you created an issue after our conversation on X. I would love to see a PR for this issue! Here is a vector search extension for SQLite https://github.com/asg017/sqlite-vec that you can use

**Comment by ArchishmanSengupta** [comment]
@ysolanky hi I am currently working on this issue, it's not completed yet(at least couldn't see any PRs)

**Comment by manthanguptaa** [comment]
I have reopened the issue @ArchishmanSengupta.

**Comment by manthanguptaa** [comment]
Hey @ArchishmanSengupta, how far ahead you are in implementing it? This is of high priority right now and would love to get this merged as soon as possible.

**Comment by josemcorderoc** [comment]
Hi, is this feature implemented? Couldn't find anything in the docs.
