### ISSUE TITLE
Enable reranking for all vectordb instances in search

### ISSUE THREAD

**Issue by osushinekotan** [phidatahq/phidata#1416]
##  Issue
- Currently, the reranker can only be set up with lancedb, but its behavior is unstable (using CohereReranker did not perform as expected).
- Additionally, it’s not possible to set a reranker for vectordb instances other than lancedb.

## Solution
- Implement a common reranker as phi.reranker.
- Add CohereReranker to `phi.reranker.cohere.py`, allowing rerankers to be set up across different vectordb instances.
- The following implementation is envisioned:

```python
if self.reranker:
      search_results = self.reranker.rerank(query=query, documents=search_results)
```

**Comment by manthanguptaa** [comment]
This is merged now @osushinekotan! Thanks for this amazing PR!
