### ISSUE TITLE
Add Docker Container Support

### ISSUE THREAD

**Issue by zapgroupdev** [phidatahq/phidata#1422]
Similar to Autogen's DockerCommandLIneCodeExecutor to replace local code runs

**Comment by manthanguptaa** [comment]
Hey @zapgroupdev, I am trying to understand your requirements more here. Do you mean you want the ability to run the cookbook examples in docker containers?

**Comment by zapgroupdev** [comment]
Autogen has this method called DockefCommandLineExecutor that works with a
programming agent to run code developed in a docker container to avoid
local runs and mitigate risk of malicious code. Current impediment of
Phidata’s Python tooling and agent is local runs. I’d like the ability to
run the code in a docker container so I can deploy my current program. Does
that help clarify?

**Comment by zapgroupdev** [comment]
So for example I'd have PythonAgent output code developed and in a conversation pass it to DockerExecutor which builds a container based on an app image to run the code and return the output.

**Comment by manthanguptaa** [comment]
@zapgroupdev so a docker tool support should be good I guess?

**Comment by vanetreg** [comment]
> @zapgroupdev so a docker tool support should be good I guess?

Yes, in Autogen AFAIK it's the default that generated code runs in a separate Docker container
https://microsoft.github.io/autogen/0.2/blog/2024/01/23/Code-execution-in-docker/
, but also in CrewAI it's configurable.

**Comment by dirkbrnd** [comment]
> > @zapgroupdev so a docker tool support should be good I guess?
> 
> Yes, in Autogen AFAIK it's the default that generated code runs in a separate Docker container
> https://microsoft.github.io/autogen/0.2/blog/2024/01/23/Code-execution-in-docker/
> , but also in CrewAI it's configurable.

Yeah I agree this is a valuable addition.
We'll take a look at it, thanks for bringing it up again!
