### ISSUE TITLE
How is telemetry data being collected and used?

### ISSUE THREAD

**Issue by jacobweiss2305** [phidatahq/phidata#1424]
Hello, I was wondering how telemetery data is being collected and used?

I have some applications were I need to keep the data completely private. 

  | 2024-11-11T12:27:25.874Z2024-11-11 12:27:25,874 - httpx - INFO - HTTP Request: POST https://api.phidata.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK" | 2024-11-11 12:27:25,874 - httpx - INFO - HTTP Request: POST https://api.phidata.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"

**Comment by ysolanky** [comment]
Hey @jacobweiss2305 !

With telemetry set to true, only the metrics related to token usage and time taken are collected by phidata. The intended use is to track the overall usage. 

You can set `telemetry = false` to disable all logging.

**Comment by jacobweiss2305** [comment]
Thanks @ysolanky !
