### ISSUE TITLE
Example with knowledge ollama requests OpenAI key?

### ISSUE THREAD

**Issue by trfetzer** [phidatahq/phidata#1459]
I am running this example line-for-line:

cookbook/providers/ollama_tools/knowledge.py

but it throws an error:

ERROR    Error processing document 'ThaiRecipes': The api_key client option must be set either by passing api_key  
         to the client or by setting the OPENAI_API_KEY environment variable                                       

Or is there an intermediate step that is e.g. creating embeddings via OpenAI that is not explicitly mentioned in this example?

**Comment by trfetzer** [comment]
Just to be clear it seems to be accessing stuff:

INFO     Creating collection                                                                                       
INFO     Loading knowledge base                                                                                    
INFO     Reading: https://phi-public.s3.amazonaws.com/recipes/ThaiRecipes.pdf                                      
ERROR    Error processing document 'ThaiRecipes': The api_key client option must be set either by passing api_key  
         to the client or by setting the OPENAI_API_KEY environment variable

**Comment by MANISH007700** [comment]
In order to run any Proprietary LLM, you need to access the model. To access the model, the only way is to use the `API key` from the respective org which you are using [in this case it's OpenAI].

Go to `https://platform.openai.com/settings/organization/api-keys` and create a new API key.

Set the `OPENAI_API_KEY` with your API key and re-execute the code. It should work fine then.

Thank you

cc @ashpreetbedi

**Comment by trfetzer** [comment]
Thanks -- but this is using an open source model -- llama3.2 via Ollama, I
do not see why there is a need for an OpenAI key to access a local llama3.2
installation as there should be no traffic via the OpenAI API at all in
this example.

**Comment by MANISH007700** [comment]
Got it. I thought it was regarding the proprietory model. 
Can you just set the ENV key and check if that's working, Irrespective of whether it's needed or not. 

But yes, for OSS models, OpenAI key seems unnecessary. 
@ashpreetbedi @manthanguptaa can look in it. Thanks

**Comment by manthanguptaa** [comment]
Hey @trfetzer, you must provide an Ollama embedder to the PgVector class. By default, it uses OpenAIEmbedder if not given by the user. So it should look like this
```
from phi.agent import Agent
from phi.embedder.ollama import OllamaEmbedder
from phi.model.ollama import OllamaTools
from phi.knowledge.pdf import PDFUrlKnowledgeBase
from phi.vectordb.pgvector import PgVector

db_url = "postgresql+psycopg://ai:ai@localhost:5532/ai"

knowledge_base = PDFUrlKnowledgeBase(
    urls=["https://phi-public.s3.amazonaws.com/recipes/ThaiRecipes.pdf"],
    vector_db=PgVector(table_name="recipes", db_url=db_url, embedder=OllamaEmbedder(model="enter model you want")),
)
knowledge_base.load(recreate=False)  # Comment out after first run

agent = Agent(
    model=OllamaTools(id="llama3.2:latest"),
    knowledge_base=knowledge_base,
    use_tools=True,
    show_tool_calls=True,
)
agent.print_response("How to make Thai curry?", markdown=True)
```

Let me know if you run into any issue
