### ISSUE TITLE
Feature Proposal: Support Passing Images as Base64 in `agent.print_response` [ Official Standard Way ]

### ISSUE THREAD

**Issue by MANISH007700** [phidatahq/phidata#1460]
**Description**

Currently, the method `add_images_to_message_content` supports adding images to message content through URLs. 
- While the method already processes these inputs effectively, there is room for improvement to better support the use of **base64-encoded images, Read PIL Image and also Byte Image.** 

The goal is to make it easier to directly pass base64-encoded image strings as input without requiring prior manual validation or transformations. This would streamline workflows for users who already work with base64 images in their pipelines.

Proposed Changes
Update the `agent.print_response` functionality to explicitly accept and process `base64-encoded image strings`.
Modify the logic in `add_images_to_message_content` to prioritize and validate base64 strings more robustly.

**PREVIEW CODE** 
```
agent.print_response(
    [
        {"type": "text", "text": "What's in this image, describe in 1 sentence"},
        {
            "type": "image_url",
            "image_url": f"data:image/jpeg;base64,{base64_string}",
        },
    ]
)
```
Lmk if you want me to pick this up and will get it done. 

cc : @manthanguptaa @ashpreetbedi

**Comment by ysolanky** [comment]
@MANISH007700 that is a great catch! Please feel free to take this up. I look forward to reviewing your PR! Thank you!

**Comment by MANISH007700** [comment]
@ysolanky can you check this issue first - [Viz Model Hallucination](https://github.com/phidatahq/phidata/issues/1481)
I'll push the new code after this issue is resolved. 

Thanks

**Comment by manthanguptaa** [comment]
@MANISH007700 look for our 2.6.0 release. We now support images and audio (video coming soon)
