### ISSUE TITLE
Print Agent workflow output

### ISSUE THREAD

**Issue by techthiyanes** [phidatahq/phidata#1461]
Could you please share the code snippet to display agent work flow output from run?
As of now, pprint response is showing the sequential steps of the output.

After completing the workflow, the output of workflow is being packed as generator object. 

May we know how could we extract the workflow output as proper variable at outside?

As similar as agent.run() where output can be retrieved from this variable's. content output.

**Comment by manthanguptaa** [comment]
Hey @techthiyanes,
If you are streaming then
```
report: Iterator[RunResponse] = HackerNewsReporter(debug_mode=False).run(num_stories=5)

for chunk in report:
    print(chunk.content)
```
will work for you. And if it's non-streaming then 
```
report: RunResponse = HackerNewsReporter(debug_mode=False).run(num_stories=5)
print(report)
```
will work for you. Let me know if this works for you.

**Comment by techthiyanes** [comment]
Though I was still getting blank output as per above code snippet so i stored the results into sql memory then returned the result in terms of sessions

**Comment by techthiyanes** [comment]
Thank you for sharing the snippet. I’m really quite impressed with the agent output of phidata.
