### ISSUE TITLE
Add Baidu Search as a Tool

### ISSUE THREAD

**Issue by Vist233** [phidatahq/phidata#1462]
I propose the integration of Baidu Search as a tool in Phidata to enhance its capabilities for users who rely on Baidu for information retrieval, particularly in regions where it is a primary search engine. This feature would make Phidata more globally accessible and versatile.

1. Regional Relevance: Baidu is the dominant search engine in China and serves millions of users daily. Adding support for it would make Phidata more applicable in this market.
2. Enhanced Diversity: With tools like DuckDuckGo already supported, adding Baidu would expand the scope of search capabilities to cater to different user preferences and regional needs.
3. Complementing Use Cases: Many assistants could benefit from localized, region-specific search results Baidu specializes in, such as localized business data, news, and language-specific resources.

If this issue aligns with the project's goals, I would be happy to work on it. Please feel free to assign the task to me directly, and I will ensure it is completed efficiently.

**Comment by manthanguptaa** [comment]
Hey @Vist233, this sounds like a perfect addition to Phidata! I am happy to assign this to you to work on. I really look forward to your PR
