### ISSUE TITLE
Vision Model Hallucinates : Gpt4o, Llava. 

### ISSUE THREAD

**Issue by MANISH007700** [phidatahq/phidata#1481]
Been using multiple vision model, gpt-4o, llava and other model. None of them are performing as expected. 

Image used - [IMAGE](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg)

Code
```
terminal --
ollama pull llava

editor --
from phi.agent import Agent
from phi.model.ollama import Ollama

image_agent = Agent(
    name="Image Understanding Agent",
    role="Analyze and understand images",
    agent_id="image-agent",
    model=Ollama(id="llava"),  # Using llava model which supports image analysis
    markdown=True,
)

image_agent.print_response(
    [
        {"type": "text", "text": "What's in this image, describe in 1 sentence"},
        {
            "type": "image_url",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
        },
    ]
)
```

Output Response
```
┃ To analyze an image, I would first observe the overall composition and elements present in the photo. This includes examining the subject matter, lighting, colors,  ┃
┃ textures, shapes, and patterns.                                                                                                                                      ┃
┃                                                                                                                                                                      ┃
┃ Next, I would consider any potential distractions or objects that may take away from the main focus of the photo. For example, if there is a busy background, it     ┃
┃ might be beneficial to crop or adjust the image to draw more attention to the subject.                                                                               ┃
┃                                                                                                                                                                      ┃
┃ After this initial assessment, I would look for any potential opportunities to enhance the image further. This could include adjusting the exposure, contrast, and   ┃
┃ saturation to make the photo pop more or using filters or editing techniques to add a unique touch.                                                                  ┃
┃                                                                                                                                                                      ┃
┃ Overall, analyzing an image involves paying attention to all aspects of the composition, subject matter, and technical elements in order to create a visually        ┃
┃ appealing and impactful photograph.  
```

Same issue was also found here - [Issue-1348](https://github.com/phidatahq/phidata/issues/1348)

Please have a look @manthanguptaa @ysolanky 
Thanks

**Comment by manthanguptaa** [comment]
Hey @MANISH007700, this is a hit-and-miss situation that I have also found to be true. Do you have a suggested solution for this?

**Comment by MANISH007700** [comment]
The Models are straightly being loaded from the HfHub, Ollama, OpenAI [no loading here though] or somewhere else. 
So the Issue is not from the model side. 

The issue arises either how model does the inference or the image passed via the codebase. 
Need to look deeply into the `image` params of the .print_response

Let me try running the code via the source rather than pypi and check it out. 
@manthanguptaa

**Comment by MANISH007700** [comment]
I did check into the codebase, and I wasn't able to figure out the reason for why this is happening. 

One thing I noticed was, Inside `Chat.py File` -> `_handle_tool_calls` : The Arg : **model_response** was not passing any response from the LLMs and it was always "". This might be the reason, but I am not sure 

cc : @manthanguptaa

**Comment by ysolanky** [comment]
@MANISH007700 This is a good catch. Please give us till the end of the week to look into this. Thank you

**Comment by ashpreetbedi** [comment]
looking

**Comment by ashpreetbedi** [comment]
this should be fixed in the next release

**Comment by MANISH007700** [comment]
Awesome, what was the issue exactly ? @ashpreetbedi
