### ISSUE TITLE
[Feature Request]: add agents workflow gui similar to that of Langgraph Studio

### ISSUE THREAD

**Issue by Don-Yin** [phidatahq/phidata#1496]
Hi, apologies if this is the wrong place of posting feature request

I wonder if there is any way to design the agents to pass information between each other in a more systematic manner and show it in a flow-like diagram in real time, just like that of the langgraph studio? 

The current way of doing it would is having one `router' node coordinating all the other agents node in a 1-leader team structure with the following setup:

```python
agent_team = Agent(
    team=[web_agent, finance_agent],
    model=OpenAIChat(id="gpt-4o"),
    instructions=["Always include sources", "Use tables to display data"],
    show_tool_calls=True,
    markdown=True,
)
```
is my understanding correct?

Is there any plan of adding a more segregated way of coordinating between them and having a UI for this?

e.g.,
![image](https://github.com/user-attachments/assets/d0e8ba81-8bc2-4ba6-bf9d-2e8af111bb4b)

**Comment by ysolanky** [comment]
Hello @Don-Yin !

Yes, your understanding that the 1 lead Agent coordinates all other Agents is correct. We support another multi Agent framework called Workflows that allows for a custom flow of information between Agents. Read more here: https://docs.phidata.com/workflows

About the UI, it looks like a great feature and it is something that is in our roadmap!

**Comment by Don-Yin** [comment]
Thank you so much for response Ysolanky that sounds reassuring! 

Best
