### ISSUE TITLE
Issue with phidata Agent UI 

### ISSUE THREAD

**Issue by varshil1008** [phidatahq/phidata#1500]
I am getting an error when I try to attach the endpoint to the AgentUI

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "\phidata\venv\Lib\site-packages\starlette\responses.py", line 259, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "\phidata\venv\Lib\site-packages\starlette\responses.py", line 255, in wrap
    await func()
  File "\phidata\venv\Lib\site-packages\starlette\responses.py", line 232, in listen_for_disconnect      
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "\phidata\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 563, in receive  
    await self.message_event.wait()
  File "C:\Program Files\Python311\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 2d9e990e0d0

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "\phidata\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "\phidata\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__   
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "\phidata\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__       
  |     raise exc
  |   File "\phidata\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__       
  |     await self.app(scope, receive, _send)
  |   File "\phidata\venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "\phidata\venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response  
  |     await self.app(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__    
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app    
  |     raise exc
  |   File "\phidata\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app    
  |     await app(scope, receive, sender)
  |   File "\phidata\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app    
  |     raise exc
  |   File "\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app    
  |     await app(scope, receive, sender)
  |   File "\venv\Lib\site-packages\starlette\routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "\phidata\venv\Lib\site-packages\starlette\responses.py", line 252, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "\phidata\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "\phidata\venv\Lib\site-packages\starlette\responses.py", line 255, in wrap
    |     await func()
    |   File "\phidata\venv\Lib\site-packages\starlette\responses.py", line 244, in stream_response      
    |     async for chunk in self.body_iterator:
    |   File "\phidata\venv\Lib\site-packages\phi\playground\router.py", line 244, in chat_response_streamer
    |     async for run_response_chunk in run_response:
    |   File "\phidata\venv\Lib\site-packages\phi\agent\agent.py", line 1969, in _arun
    |     async for model_response_chunk in model_response_stream:  # type: ignore
    | TypeError: 'async for' requires an object with __aiter__ method, got coroutine
    +------------------------------------
\phidata\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py:-1: RuntimeWarning: coroutine 'Model.aresponse_stream' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by manthanguptaa** [comment]
Hey @varshil1008, by attaching an endpoint do you mean you were adding a custom endpoint in the playground?

**Comment by manthanguptaa** [comment]
That shouldn't be the case @varshil1008. Can you run `pip install -U phidata` and try running again?

**Comment by Se1toku** [comment]
Have you tried removing `add_history_to_messages=True,`?

**Comment by AntonioStipic** [comment]
Asking to reopen since this issue is still present in version `2.7.5`

I have following example code (Adjusted to call Gemini instead of OpenAI)


```python
from phi.agent import Agent
from phi.model.google import Gemini
from phi.storage.agent.sqlite import SqlAgentStorage
from phi.tools.duckduckgo import DuckDuckGo
from phi.tools.yfinance import YFinanceTools
from phi.playground import Playground, serve_playground_app

web_agent = Agent(
    name="Web Agent",
    model=Gemini(id="gemini-1.5-pro", api_key="XXX"),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    storage=SqlAgentStorage(table_name="web_agent", db_file="agents.db"),
    add_history_to_messages=True,
    markdown=True,
)

finance_agent = Agent(
    name="Finance Agent",
    model=Gemini(id="gemini-1.5-pro", api_key="XXX"),
    tools=[YFinanceTools(stock_price=True, analyst_recommendations=True, company_info=True, company_news=True)],
    instructions=["Use tables to display data"],
    storage=SqlAgentStorage(table_name="finance_agent", db_file="agents.db"),
    add_history_to_messages=True,
    markdown=True,
)

app = Playground(agents=[finance_agent, web_agent]).get_app()

if __name__ == "__main__":
    serve_playground_app("playground:app", reload=True)
```

And this is the error I receive when sending any message from www.phidata.app/playground/chat?endpoint=localhost%253A7777

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/responses.py", line 259, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
    await func()
  File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/responses.py", line 232, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 531, in receive
    await self.message_event.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1298c0ad0

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
  |     raise exc
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 144, in simple_response
  |     await self.app(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/responses.py", line 252, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
    |     await func()
    |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/starlette/responses.py", line 244, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/phi/playground/router.py", line 400, in chat_response_streamer
    |     async for run_response_chunk in run_response:
    |   File "/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/phi/agent/agent.py", line 2149, in _arun
    |     async for model_response_chunk in model_response_stream:  # type: ignore
    | TypeError: 'async for' requires an object with __aiter__ method, got coroutine
    +------------------------------------
/Users/antoniostipic/Desktop/playground/phidata-test/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py:-1: RuntimeWarning: coroutine 'Model.aresponse_stream' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

The issue @tobalo is referencing is that Brave browser cannot access `http:localhost:7777` when Brave Shields are activated.

**Comment by manthanguptaa** [comment]
@AntonioStipic 

```
from phi.agent import Agent
from phi.model.google import Gemini
from phi.storage.agent.sqlite import SqlAgentStorage
from phi.tools.duckduckgo import DuckDuckGo
from phi.tools.yfinance import YFinanceTools
from phi.playground import Playground, serve_playground_app

web_agent = Agent(
    name="Web Agent",
    model=Gemini(id="gemini-1.5-pro", api_key="XXX"),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    storage=SqlAgentStorage(table_name="web_agent", db_file="agents.db"),
    add_history_to_messages=True,
    markdown=True,
)

finance_agent = Agent(
    name="Finance Agent",
    model=Gemini(id="gemini-1.5-pro", api_key="XXX"),
    tools=[YFinanceTools(stock_price=True, analyst_recommendations=True, company_info=True, company_news=True)],
    instructions=["Use tables to display data"],
    storage=SqlAgentStorage(table_name="finance_agent", db_file="agents.db"),
    add_history_to_messages=True,
    markdown=True,
)

app = Playground(agents=[finance_agent, web_agent]).get_app(use_async=False)

if __name__ == "__main__":
    serve_playground_app("playground:app", reload=True)
```


Try this out

**Comment by AntonioStipic** [comment]
@manthanguptaa Thank you, using `use_async=False` fixes this error

**Comment by ERICK-ZABALA** [comment]
app = Playground(agents=[agent]).get_app(use_async=False)
