### ISSUE TITLE
Implement document_lists in AgentKnowledge

### ISSUE THREAD

**Issue by navopw** [phidatahq/phidata#1502]
load method fails because document_lists throws NotImplementedError.

**Comment by manthanguptaa** [comment]
Hey @navopw, you have to use `DocumentKnowledgeBase` to pass `document_lists`. Here are the docs for it https://docs.phidata.com/knowledge/document

**Comment by navopw** [comment]
Oh thank you, let me try!

**Comment by navopw** [comment]
Worked fine but the example has to be updated, its has no path="data/docs",

Instead provide a list of Document.
