### ISSUE TITLE
something is wrong with  Website_Assistant

### ISSUE THREAD

**Issue by fengyunzaidushi** [phidatahq/phidata#151]
https://demo.aidev.run/Website_Assistant
![image](https://github.com/phidatahq/phidata/assets/53250064/0fc1ce2c-e760-4435-9a12-796a86c293fd)

**Comment by ashpreetbedi** [comment]
thanks for the bog @fengyunzaidushi, will check today

**Comment by ashpreetbedi** [comment]
@fengyunzaidushi sadly its now able to read github repo content. we're working on a fix for this
