### ISSUE TITLE
It is possible to work with mem0?

### ISSUE THREAD

**Issue by whisper-bye** [phidatahq/phidata#1523]
as the title.

**Comment by manthanguptaa** [comment]
Hey @whisper-bye, we currently don't have an integration with mem0. Can you help me with your use case? Something that Phidata already supports out of the box maybe of help to you. Nonetheless, I will bring this up with the team and see what we can do

**Comment by whisper-bye** [comment]
mem0 as pluggable agent's memory layer.

**Comment by ysolanky** [comment]
Hey @whisper-bye! Thanks for this feature request. We will be adding an integration with mem0. Please stay tuned for updates soon!

**Comment by konavai** [comment]
Is this already integrated?

**Comment by kaanberke** [comment]
For whom requires mem0 integration with agno, check this out:

https://github.com/agno-agi/agno/blob/0ec58b81c0eb827c505ab211ab75aadf4f9a38e2/cookbook/agent_concepts/memory/08_mem0_memory.py#L4
