### ISSUE TITLE
azure open ai model as Agent llm

### ISSUE THREAD

**Issue by sureshtmca** [phidatahq/phidata#1530]
Hi 
tried to use Azure Open ai model using 

azure_model = AzureOpenAIChat(
    id=os.getenv("AZURE_OPENAI_MODEL_NAME"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    azure_deployment=os.getenv("AZURE_OPENAI_DEPLOYMENT"),
)

but not working. Model not found is the issue occuring. For me, Deployment name is nothing but devgpt4o so what is model name then. Also Endpoint is only base url or full end point with version number included ? please suggest or provide any sample

**Comment by ysolanky** [comment]
Hello @sureshtmca ! Please export the following variables to use Azure OpenAI:

```
export AZURE_DEPLOYMENT=***
export AZURE_OPENAI_API_KEY=***
export AZURE_OPENAI_ENDPOINT=***
export AWS_DEFAULT_REGION=us-east-1
```

Please let us know if you are still facing issues

**Comment by sureshtmca** [comment]
Thanks @ysolanky ... though export was used , not working earlier. same earlier setup ,  now works.

Your golden hand, all working Brother  :)... Thank you

**Comment by infinitelyloopy-bt** [comment]
> Hello [@sureshtmca](https://github.com/sureshtmca) ! Please export the following variables to use Azure OpenAI:
> 
> ```
> export AZURE_DEPLOYMENT=***
> export AZURE_OPENAI_API_KEY=***
> export AZURE_OPENAI_ENDPOINT=***
> export AWS_DEFAULT_REGION=us-east-1
> ```
> 
> Please let us know if you are still facing issues

Curious to know, why use the export features vs. creating a local .env file?

**Comment by ysolanky** [comment]
@infinitelyloopy-bt I personally use an .envrc file with direnv. I'd also recommend use of the same instead of exporting variables every time
