### ISSUE TITLE
Please add cached_tokens for OpenAI models

### ISSUE THREAD

**Issue by KevinZhang19870314** [phidatahq/phidata#1535]
Please add cached_tokens for OpenAI models, see [api-prompt-caching](https://openai.com/index/api-prompt-caching/)

**Comment by ysolanky** [comment]
Hello! @KevinZhang19870314 prompt caching via OpenAI api is automatic. No changes need to be made on our end. If you enable debug logs, you can also view the number of cached tokens
`* Prompt tokens details:       {'audio_tokens': 0, 'cached_tokens': 0} `
