### ISSUE TITLE
Blurry Playground Dialog

### ISSUE THREAD

**Issue by MichaelXF** [phidatahq/phidata#1536]
![image](https://github.com/user-attachments/assets/3df093dc-3a7b-4b8b-8140-b2d8f0fff65f)
![image](https://github.com/user-attachments/assets/641548c1-c2fc-4b7e-a18d-7cb2c82b5699)

It may be hard to tell from the screenshot but there is a blur over the dialog content. Removed blur effect through Inspect Element in 2nd image. Using Chrome.

**Comment by pritipsingh** [comment]
@MichaelXF Thanks for flagging this- we really love a clean UI as well! I’ve created a PR to fix this issue.
