### ISSUE TITLE
Could not import module Playground

### ISSUE THREAD

**Issue by arcontechnologies** [phidatahq/phidata#1541]
When running the playground.py example, I'm getting this error that prevent the agents to be loaded into the UI.

![image](https://github.com/user-attachments/assets/669b1773-d511-4fd3-aba5-344cc9677353)

Any insight ?

**Comment by jcbsorensen** [comment]
Getting the same error. I use the playground.py example as well. However slightly modified with 1 agent and using ollama.

**Comment by manthanguptaa** [comment]
Hey @jcbsorensen @arcontechnologies, can you confirm if this is the example you both tried running? 
https://github.com/phidatahq/phidata/blob/main/cookbook/agents/06_playground.py

**Comment by arcontechnologies** [comment]
hi, @manthanguptaa . I can confirm that the issue is still there :
![image](https://github.com/user-attachments/assets/894ea188-619e-463a-ba95-9baa0da01323)
I took your code and I did a full pip installation.
I running under windows 11.

**Comment by manthanguptaa** [comment]
@arcontechnologies what's the name of the file your code resides in?

**Comment by arcontechnologies** [comment]
the name of the file is "agent_ui_app.py"
