### ISSUE TITLE
Please add an example agent that generates timestamp of a longer youtube video.

### ISSUE THREAD

**Issue by samyogdhital** [phidatahq/phidata#1553]
I was not able to get timestamp of any video from youtube agent from the example folder.
It only summarizes the content of the video.
It is likely that everyone would appreciate having an AI generate timestamps for a lengthy podcast if the creator hasn't added that on YouTube.

**Comment by manthanguptaa** [comment]
Hey @samyogdhital, we are on it!

**Comment by manthanguptaa** [comment]
Check this out @samyogdhital 
https://github.com/phidatahq/phidata/blob/main/cookbook/agents/46_generate_yt_timestamps.py

**Comment by samyogdhital** [comment]
@manthanguptaa its works but we have a problem, I think agents are just getting captions and not the information about exact time when the sentence was said.

And thus the timestamp given by agent are significantly longer and shorter than original video.
The timestamps timings are not accurate at all.

I think the problem is with `YoutubeTools`. I think it does not provide the information about length of the video and captions with exact time at all.

Is this `YoutubeTools` package developed by you guys at phidata or it is some external package?
- If we are able to get `.srt` file of a youtube video and work with that then this problem will be solved. `.srt` file has transcription with exact timing in it.


If this can be solvable then please re-open the issue.
