### ISSUE TITLE
 Could storing historical records in a dedicated table improve performance?

### ISSUE THREAD

**Issue by yingce** [phidatahq/phidata#1555]
First of all, I appreciate the hard work that has gone into developing this project. I have a question regarding the storage of historical records using the jsonb format in PostgreSQL or SQLite.

Currently, historical data is stored as jsonb, which is efficient for certain use cases. However, I'm curious if storing large amounts of historical data in a single column could potentially impact performance, especially as the data grows.

Would it be possible to consider storing historical records in a separate table? This way, when adding a record to num_history_responses, we can efficiently query only the most recent data.

Thank you for considering my inquiry. I'm looking forward to your insights on this matter.

Best regards

**Comment by ysolanky** [comment]
Hey @yingce! First of all, thank you for your kind words. 

I get the concern—storing a lot of historical data in a single jsonb column might seem like it could cause performance issues as the data grows. But in short: we should not underestimate PostgreSQL. It is more than capable of handinling nested jsonb format

While storing historical records in a separate table could work, it adds complexity with joins and schema management. Unless we hit a clear bottleneck, the jsonb approach is solid and keeps things flexible.

**Comment by yingce** [comment]
Got it, I appreciate your response.
