### ISSUE TITLE
Tools -> Youtube -> Missing Proxy parameter

### ISSUE THREAD

**Issue by ventz** [phidatahq/phidata#1567]
Hi,

Could you please expose the `proxies` parameter at:
https://docs.phidata.com/tools/youtube

So that a proxy can be passed to:

```
proxies={"https": "http://localhost:8080"}
transcript = YouTubeTranscriptApi.get_transcript(video_id, proxies)
```

YouTube blocks/filters most of the cloud providers, and this ends up breaking this module when trying to use from a Lambda/Serverless/Container/etc

CC: @manthanguptaa @ysolanky

**Comment by ysolanky** [comment]
Hey @ventz added the proxy param here: https://github.com/phidatahq/phidata/pull/1568

**Comment by ventz** [comment]
@ysolanky Thank you! (that was too fast ;))

**Comment by ventz** [comment]
@dirkbrnd Thanks. Could you also push out a new pip build: https://pypi.org/project/youtube-transcript-api/#history

**Comment by ventz** [comment]
@ysolanky Just to confirm, this would be the example usage, yes?

```
# Construct the proxy URLs with authentication
http_proxy = f"http://{proxy_username}:{proxy_password}@{proxy_host}:{proxy_port}"

proxies = { "http": http_proxy }

agent = Agent(
    tools=[YouTubeTools(proxies=proxies)],
    ...
)
```

Asking because on `phidata 2.7.4` I am not seeing that working.
