### ISSUE TITLE
How to create own tool

### ISSUE THREAD

**Issue by balavenkatesh3322** [phidatahq/phidata#157]
I want to call generate_report function with app name parameter. How to create own function and configure with assistant. 

Please give me some sample code or reference link.

**Comment by balavenkatesh-ai** [comment]
I found it. sorry for creating as issue. Please close it. Thanks.

**Comment by ashpreetbedi** [comment]
Thanks [balavenkatesh-ai](https://github.com/balavenkatesh-ai)
