### ISSUE TITLE
SQLTools(db_url=db_url, run_sql_query=True) error

### ISSUE THREAD

**Issue by alfredwallace7** [phidatahq/phidata#1585]
I want to start by thanking the contributors and maintainers of this incredible library. Your hard work empowers developers like me to achieve more. I'm truly grateful for your contributions to the open-source community, thank you!

Using these versions:
phidata==2.7.3
openai==1.57.4

I get this error when trying to use the run_sql_query tool :
`openai.BadRequestError: Error code: 400 - {'error': {'message': 'json: cannot unmarshal array into Go struct field .tools.function.parameters.properties.type of type string', 'type': 'invalid_request_error', 'param': None, 'code': None}}`

Proposed solution that works for me is modifying phi/tools/sql.py file:

```
--- sql.py (original)
+++ sql.py (fixed)
@@ -1,7 +1,7 @@
 import json
 from typing import List, Optional, Dict, Any
 
-from phi.tools import Toolkit
+from phi.tools import Toolkit, Function
 from phi.utils.log import logger
 
 try:
@@ -57,7 +57,11 @@
         if describe_table:
             self.register(self.describe_table)
         if run_sql_query:
-            self.register(self.run_sql_query)
+            # Register run_sql_query function with explicit schema
+            run_sql_query_func = lambda query, limit=10: self.run_sql_query(query=query, limit=limit)
+            run_sql_query_func.__name__ = "run_sql_query"
+            run_sql_query_func.__doc__ = "Run a SQL query and return the results"
+            self.register(run_sql_query_func)
```

Hope it helps someone.

**Comment by manthanguptaa** [comment]
Hey @alfredwallace7, I wasn't able to replicate this issue. I ran this script and it worked perfectly 
```
from phi.agent import Agent
from phi.tools.sql import SQLTools

db_url = "postgresql+psycopg://ai:ai@localhost:5532/ai"

agent = Agent(tools=[SQLTools(db_url=db_url)])
agent.print_response("List the tables in the database. Tell me about contents of one of the tables", markdown=True)

```

Can you help me with the code you are trying to run?

**Comment by dirkbrnd** [comment]
@alfredwallace7 
I set up a local containerised mysql DB and ran the following script
```
from phi.agent import Agent
from phi.tools.sql import SQLTools
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv(override=True)

# Database configuration
db_url = f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@" \
         f"{os.getenv('DB_HOST')}:3306/{os.getenv('DB_NAME')}"


# Agent setup
agent = Agent(tools=[SQLTools(db_url=db_url)])

# Query execution
agent.print_response("List the tables in the database. Tell me about contents of one of the tables", markdown=True)

```

And this worked for me without any errors.  Note the default model is OpenAIChat so the above should match your setup exactly, except that I used a containerised MySQL with some manually added tables
