### ISSUE TITLE
Error reading environment variable? 

### ISSUE THREAD

**Issue by hemanth** [phidatahq/phidata#1587]
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/8d5d784b-239b-4f2b-9f3d-cbc8c8c7c42a" />

**Comment by manthanguptaa** [comment]
Hey @hemanth, I am not sure about the interface on left-hand side that you are using to set environment variables but you can try running `export HF_TOKEN=****` in your terminal to set your token. Right now it's not getting set correctly

**Comment by hemanth** [comment]
@manthanguptaa this is on google colab. 

<img width="766" alt="image" src="https://github.com/user-attachments/assets/79a0a3de-0d82-4e0d-9572-835303bf4af0" />

**Comment by manthanguptaa** [comment]
@hemanth another thing you can do is pass the API key directly to the `HuggingFaceChat` class. For this reason, the param `api_key` is present in the class.

**Comment by hemanth** [comment]
>You can also maybe try setting the environment variable using this %env HF_TOKEN=*****

https://github.com/phidatahq/phidata/issues/1587#issuecomment-2549593570
