### ISSUE TITLE
Calling tools multiple times

### ISSUE THREAD

**Issue by balavenkatesh-ai** [phidatahq/phidata#160]
I'm facing an issue with the tool call limit. I've set tool_call_limit = 2 in our code, but the tool keeps getting called continuously without giving response.

particularly, if i say no then it's start executing many times.

I've double-checked the variable assignment and reviewed the relevant code logic, but I can't seem to identify the cause.

Could someone help me troubleshoot this? Any insights or suggestions on how to enforce the call limit effectively would be greatly appreciated.

**Comment by ashpreetbedi** [comment]
@balavenkatesh-ai please can you share the code?

Depending on the LLM provider, its possible that the [deactivation of tool call](https://github.com/phidatahq/phidata/blob/main/phi/llm/base.py#L120-L123) isnt being respected. If you share the code then i can help debug

**Comment by balavenkatesh-ai** [comment]
@ashpreetbedi . This is my config. sometimes it's very specific to hi,hello, okay prompt. 

`assistant = Assistant(
    #llm=Ollama(model="openhermes", host="http://10.16.1.10:11434", keep_alive=-1),
    #llm=Ollama(model="openhermes", host="http://10.0.15.6:11434", keep_alive=-1),
    llm=Ollama(model="llama-function:latest", host="http://10.0.15.6:11434", keep_alive=-1),
    #llm=Ollama(model="llama2:chat", host="http://10.0.15.6:11434", keep_alive=-1),
    tools=[generate_msbr_report,guardian_copilot_definition,get_ci_id_by_app_name,get_component_details_by_app_name],
    use_tools=False,
    tool_call_limit = 1,
    show_tool_calls =False,
    debug_mode=True,
    tool_choice = "auto",
    add_chat_history_to_prompt = True,
    num_history_messages = 2,`

**Comment by balavenkatesh-ai** [comment]
@ashpreetbedi @adieyal @bmorphism @ivanfioravanti  it's very critical issues. can you please look into this?

**Comment by ashpreetbedi** [comment]
@balavenkatesh-ai we can resolve this in our call today -- this is a model limitation as `llama-function` might not be a good enough model. Have you tried [Hermes2 Pro](https://github.com/phidatahq/phidata/tree/main/cookbook/hermes2) here?

**Comment by balavenkatesh3322** [comment]
@ashpreetbedi Yes. I am using herms pro only. Suddenly it's keep on running for prompt input.

**Comment by ashpreetbedi** [comment]
resolved over a call, needs to be tested with Hermes 2 Pro
