### ISSUE TITLE
Using other large models will result in an error？？？？

### ISSUE THREAD

**Issue by wwwrookie** [phidatahq/phidata#1602]
![image](https://github.com/user-attachments/assets/8042e5ba-16dc-4cdc-838c-91f5545fa375)

**Comment by wwwrookie** [comment]
ok thansk  But I used persistence .bashrc to succeed. Otherwise, closing the terminal and restarting the terminal export will fail.

**Comment by ysolanky** [comment]
@wwwrookie looks like you were able to resolve this issue. Please reopen in case you run into any problems.

**Comment by wwwrookie** [comment]
ok thanks
