### ISSUE TITLE
Response from new gemini thinking models are not showing in playground UI but can be seen in terminal in debug mode.

### ISSUE THREAD

**Issue by samyogdhital** [phidatahq/phidata#1613]
Response is there but it is not streaming into UI.

Img1 - Terminal Response
![image](https://github.com/user-attachments/assets/b75a5f91-0b1b-4ebc-badd-0a7a099f9389)

Img2 - Playground AI not streaming text from backend.
![image](https://github.com/user-attachments/assets/23a25f98-009c-42b2-b6ba-f1e8ace5c46f)

Img3 - Gemini model used
![image](https://github.com/user-attachments/assets/fc3993b7-28ee-4e32-8424-9c818bc0cfac)

**Comment by Ayush0054** [comment]
hey i tried this and it worked for me, 
![image](https://github.com/user-attachments/assets/bec8e124-be86-42e6-9ac4-e5e1f2545225)

if possible can you please share your agent configuration

thanks

**Comment by samyogdhital** [comment]
I think you are not able to do tool call with new reasoning model in gemini.

That was the reason of earlier response not working. Thanks for reply though!

Closing this issue.
