### ISSUE TITLE
integrate RAG with function calling.

### ISSUE THREAD

**Issue by balavenkatesh-ai** [phidatahq/phidata#162]
``I have integrated both rag with function calling but tools is not calling based on prompt. below is my configurations.

`rag_with_function_assistant = Assistant(
    llm=Ollama(model="openhermes", host="http://.0.0.06:11434", keep_alive=-1),
    knowledge_base=get_knowledge_base(),
    add_references_to_prompt = True,
    tools=[generate_report,guardian_copilot_definition],
    use_tools=True,
    tool_call_limit = 1,
    show_tool_calls =True,
    debug_mode=True,
    tool_choice = "auto",
    update_knowledge_base = False,
    add_knowledge_base_instructions =True,
    add_chat_history_to_prompt = False,
    prevent_hallucinations=True,`)

**Comment by ysolanky** [comment]
@balavenkatesh-ai, can you share the debug logs? Primarily I want to check if the function is being added to the LLM. 

Additionally, incorporating a docstring into the function can significantly aid the LLM in comprehending the purpose and usage of the function.

**Comment by balavenkatesh-ai** [comment]
@ysolanky instruction and functions are not added in the prompt. why it's not appending?

**Comment by ashpreetbedi** [comment]
@balavenkatesh-ai please can you use the [Hermes2 model like this](https://github.com/phidatahq/phidata/blob/main/cookbook/hermes2/auto_rag/assistant.py#L45-L65) and share debug logs. 

Also are you open to a quick call this week/next -- we can hash out a lot of these issues in one go.

[Here's my calendar if you're open](https://book.vimcal.com/t/ashpreetbedi/30-min-a36790)

**Comment by ashpreetbedi** [comment]
resolved over a call
