### ISSUE TITLE
Dynamic tool creation broke in `2.7`

### ISSUE THREAD

**Issue by mridula-plivo** [phidatahq/phidata#1624]
I have a bunch of function definitions as a list of dictionaries. For example:

```
tools = [
    {
        "name": "create_employee",
        "parameters": ... #json schema
    },
    ...
]

```
I have a wrapper-type function that calls these tools:

```
fn = []
for tool in tools:
    def execute_tool(tool_name: str=tool['name'], **kwargs):
        ....
    
    fns.append(
        Function(name=tool['name'], parameters=tool['parameters'], entrypoint=execute_tool,....)
    )

agent = Agent(..., tools=fns, ...)
agent.run()
```

This used to work perfectly in `2.5.32`, but it stopped working in `2.7`.
The reason is, when adding the tools, the parameters that I pass are overridden by `process_entrypoint`.

Should I create a PR to fix this?

**Comment by manthanguptaa** [comment]
Hey @mridula-plivo, you can refer this to write your own custom tool 
https://docs.phidata.com/tools/custom-toolkits

**Comment by mridula-plivo** [comment]
> Hey @mridula-plivo, you can refer this to write your own custom tool https://docs.phidata.com/tools/custom-toolkits

Thanks. Bug, how can I use this for the use case I mentioned? The tools are decided dynamically at run time. So, in my example, I generate a `Function` instance per tool which call the same method.

**Comment by mridula-plivo** [comment]
@manthanguptaa That is not possible for my use case. 

I have a bunch of action definitions (the schema, and action name) and I was generating callables from it at run time. (Like in the code snippet above). 

With Toolkit, that's not possible.
