### ISSUE TITLE
How to do it http://localhost:7777/ Open the page

### ISSUE THREAD

**Issue by XiaozhiAGI** [phidatahq/phidata#1625]
How to do it http://localhost:7777/ Open the page，How to do it http://localhost:7777/ Open the page instead of being on it https://www.phidata.app/playground/chat?endpoint=localhost:7777&agent= Opening the page in the middle raises concerns about the leakage of confidential data

**Comment by manthanguptaa** [comment]
Hey @XiaozhiAGI, you can access the endpoints on `http://localhost:7777/docs`. Currently, we don't have the Agent UI open source which means that if you want to use the Agent UI you will have to open the `https://www.phidata.app/playground/chat?endpoint=localhost:7777&agent=` endpoint
