### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by balavenkatesh3322** [phidatahq/phidata#163]
1. I have podman in my system instead of docker. How can I switch to install pgvector db.

2. How to access using ip address if hosted on other server.

3. I have own docker hub space. How to give custom docker image name to pull from given repo.

**Comment by ashpreetbedi** [comment]
@balavenkatesh3322 posted on another thread but wondering if you're open to a quick call this week/next. We can hash out a lot of these issues in one go. [Here's my calendar](https://book.vimcal.com/t/ashpreetbedi/30-min-a36790)

**Comment by ashpreetbedi** [comment]
resolved over call
