### ISSUE TITLE
streamlit mistral is broken

### ISSUE THREAD

**Issue by arw357** [phidatahq/phidata#167]
It used to work since I tested it some weeks ago but now I have : 

```
Traceback (most recent call last):
  File "IdeaProjects/phidata/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "IdeaProjects/phidata/cookbook/mistral/app.py", line 13, in <module>
    from cookbook.mistral.mistral_assistant import get_mistral_assistant  # type: ignore
ModuleNotFoundError: No module named 'cookbook'
```
I follow the README:  https://github.com/phidatahq/phidata/blob/main/cookbook/mistral/README.md

**Comment by ashpreetbedi** [comment]
@arw357 this seems to be an issue with the path/environment. Please can you redo the steps after deleted the env: `rm -rf ~/.venvs/aienv` thanks

**Comment by arw357** [comment]
Did it from the beginning. 
<details><summary>Details</summary>
<p>

test @ station1 ~/IdeaProjects/phidata (main)
 rm -rf ~/.venvs/aienv
test @ station1 ~/IdeaProjects/phidata (main)
 python3 -m venv ~/.venvs/aienv
test @ station1 ~/IdeaProjects/phidata (main)
 source ~/.venvs/aienv/bin/activate
(aienv) test @ station1 ~/IdeaProjects/phidata (main)
 pip install -r cookbook/mistral/requirements.txt
Collecting altair==5.2.0
  Using cached altair-5.2.0-py3-none-any.whl (996 kB)
Collecting annotated-types==0.6.0
  Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Collecting anyio==4.3.0
  Using cached anyio-4.3.0-py3-none-any.whl (85 kB)
Collecting attrs==23.2.0
  Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Collecting blinker==1.7.0
  Using cached blinker-1.7.0-py3-none-any.whl (13 kB)
Collecting boto3==1.34.49
  Using cached boto3-1.34.49-py3-none-any.whl (139 kB)
Collecting botocore==1.34.49
  Using cached botocore-1.34.49-py3-none-any.whl (12.0 MB)
Collecting cachetools==5.3.2
  Using cached cachetools-5.3.2-py3-none-any.whl (9.3 kB)
Collecting certifi==2024.2.2
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting charset-normalizer==3.3.2
  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Collecting click==8.1.7
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting docker==7.0.0
  Using cached docker-7.0.0-py3-none-any.whl (147 kB)
Collecting gitdb==4.0.11
  Using cached gitdb-4.0.11-py3-none-any.whl (62 kB)
Collecting gitpython==3.1.42
  Using cached GitPython-3.1.42-py3-none-any.whl (195 kB)
Collecting h11==0.14.0
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting httpcore==1.0.4
  Using cached httpcore-1.0.4-py3-none-any.whl (77 kB)
Collecting httpx==0.25.2
  Using cached httpx-0.25.2-py3-none-any.whl (74 kB)
Collecting idna==3.6
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting importlib-metadata==7.0.1
  Using cached importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Collecting jinja2==3.1.3
  Using cached Jinja2-3.1.3-py3-none-any.whl (133 kB)
Collecting jmespath==1.0.1
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting jsonschema==4.21.1
  Using cached jsonschema-4.21.1-py3-none-any.whl (85 kB)
Collecting jsonschema-specifications==2023.12.1
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Collecting markdown-it-py==3.0.0
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting markupsafe==2.1.5
  Using cached MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting mdurl==0.1.2
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting mistralai==0.1.2
  Using cached mistralai-0.1.2-py3-none-any.whl (15 kB)
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Collecting orjson==3.9.15
  Using cached orjson-3.9.15-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)
Collecting packaging==23.2
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting pandas==2.2.1
  Using cached pandas-2.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
Collecting pgvector==0.2.5
  Using cached pgvector-0.2.5-py2.py3-none-any.whl (9.6 kB)
Collecting phidata==2.3.62
  Using cached phidata-2.3.62-py3-none-any.whl (550 kB)
Collecting pillow==10.2.0
  Using cached pillow-10.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
Collecting protobuf==4.25.3
  Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Collecting psycopg[binary]==3.1.18
  Using cached psycopg-3.1.18-py3-none-any.whl (178 kB)
Collecting psycopg-binary==3.1.18
  Using cached psycopg_binary-3.1.18-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Collecting pyarrow==15.0.0
  Using cached pyarrow-15.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (38.3 MB)
Collecting pydantic==2.6.2
  Using cached pydantic-2.6.2-py3-none-any.whl (394 kB)
Collecting pydantic-core==2.16.3
  Using cached pydantic_core-2.16.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
Collecting pydantic-settings==2.2.1
  Using cached pydantic_settings-2.2.1-py3-none-any.whl (13 kB)
Collecting pydeck==0.8.1b0
  Using cached pydeck-0.8.1b0-py2.py3-none-any.whl (4.8 MB)
Collecting pygments==2.17.2
  Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Collecting pypdf==4.0.2
  Using cached pypdf-4.0.2-py3-none-any.whl (283 kB)
Collecting python-dateutil==2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting python-dotenv==1.0.1
  Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Collecting pytz==2024.1
  Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting pyyaml==6.0.1
  Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
Collecting referencing==0.33.0
  Using cached referencing-0.33.0-py3-none-any.whl (26 kB)
Collecting requests==2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting rich==13.7.0
  Using cached rich-13.7.0-py3-none-any.whl (240 kB)
Collecting rpds-py==0.18.0
  Using cached rpds_py-0.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting s3transfer==0.10.0
  Using cached s3transfer-0.10.0-py3-none-any.whl (82 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting smmap==5.0.1
  Using cached smmap-5.0.1-py3-none-any.whl (24 kB)
Collecting sniffio==1.3.1
  Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting sqlalchemy==2.0.27
  Using cached SQLAlchemy-2.0.27-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting streamlit==1.31.1
  Using cached streamlit-1.31.1-py2.py3-none-any.whl (8.4 MB)
Collecting tenacity==8.2.3
  Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Collecting toml==0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting tomli==2.0.1
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting toolz==0.12.1
  Using cached toolz-0.12.1-py3-none-any.whl (56 kB)
Collecting tornado==6.4
  Using cached tornado-6.4-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435 kB)
Collecting typer==0.9.0
  Using cached typer-0.9.0-py3-none-any.whl (45 kB)
Collecting typing-extensions==4.10.0
  Using cached typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Collecting tzdata==2024.1
  Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Collecting tzlocal==5.2
  Using cached tzlocal-5.2-py3-none-any.whl (17 kB)
Collecting urllib3==2.0.7
  Using cached urllib3-2.0.7-py3-none-any.whl (124 kB)
Collecting validators==0.22.0
  Using cached validators-0.22.0-py3-none-any.whl (26 kB)
Collecting zipp==3.17.0
  Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Collecting exceptiongroup>=1.0.2
  Using cached exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Collecting greenlet!=0.4.17
  Using cached greenlet-3.0.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (616 kB)
Collecting watchdog>=2.1.5
  Using cached watchdog-4.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)
Installing collected packages: pytz, zipp, watchdog, validators, urllib3, tzlocal, tzdata, typing-extensions, tornado, toolz, tomli, toml, tenacity, sniffio, smmap, six, rpds-py, pyyaml, python-dotenv, pypdf, pygments, psycopg-binary, protobuf, pillow, packaging, orjson, numpy, mdurl, markupsafe, jmespath, idna, h11, greenlet, exceptiongroup, click, charset-normalizer, certifi, cachetools, blinker, attrs, annotated-types, typer, sqlalchemy, requests, referencing, python-dateutil, pydantic-core, pyarrow, psycopg, pgvector, markdown-it-py, jinja2, importlib-metadata, httpcore, gitdb, anyio, rich, pydeck, pydantic, pandas, jsonschema-specifications, httpx, gitpython, docker, botocore, s3transfer, pydantic-settings, mistralai, jsonschema, boto3, altair, streamlit, phidata
Successfully installed altair-5.2.0 annotated-types-0.6.0 anyio-4.3.0 attrs-23.2.0 blinker-1.7.0 boto3-1.34.49 botocore-1.34.49 cachetools-5.3.2 certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 docker-7.0.0 exceptiongroup-1.2.0 gitdb-4.0.11 gitpython-3.1.42 greenlet-3.0.3 h11-0.14.0 httpcore-1.0.4 httpx-0.25.2 idna-3.6 importlib-metadata-7.0.1 jinja2-3.1.3 jmespath-1.0.1 jsonschema-4.21.1 jsonschema-specifications-2023.12.1 markdown-it-py-3.0.0 markupsafe-2.1.5 mdurl-0.1.2 mistralai-0.1.2 numpy-1.26.4 orjson-3.9.15 packaging-23.2 pandas-2.2.1 pgvector-0.2.5 phidata-2.3.62 pillow-10.2.0 protobuf-4.25.3 psycopg-3.1.18 psycopg-binary-3.1.18 pyarrow-15.0.0 pydantic-2.6.2 pydantic-core-2.16.3 pydantic-settings-2.2.1 pydeck-0.8.1b0 pygments-2.17.2 pypdf-4.0.2 python-dateutil-2.8.2 python-dotenv-1.0.1 pytz-2024.1 pyyaml-6.0.1 referencing-0.33.0 requests-2.31.0 rich-13.7.0 rpds-py-0.18.0 s3transfer-0.10.0 six-1.16.0 smmap-5.0.1 sniffio-1.3.1 sqlalchemy-2.0.27 streamlit-1.31.1 tenacity-8.2.3 toml-0.10.2 tomli-2.0.1 toolz-0.12.1 tornado-6.4 typer-0.9.0 typing-extensions-4.10.0 tzdata-2024.1 tzlocal-5.2 urllib3-2.0.7 validators-0.22.0 watchdog-4.0.0 zipp-3.17.0
(aienv) test @ station1 ~/IdeaProjects/phidata (main)
 phi start cookbook/mistral/resources.py -y
Starting resources in: /home/test/IdeaProjects/phidata/cookbook/mistral/resources.py

-==+==- Network: phi
Network: phi already exists

-==+==- Container: pgvector
Starting container: pgvector
Container Status: running
Container: pgvector created

--**-- Resources created: 2/2

--**-- ResourceGroups deployed: 1/1

(aienv) test @ station1 ~/IdeaProjects/phidata (main)
 streamlit run cookbook/mistral/app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.229:8501

2024-04-09 06:45:23.162 Uncaught app exception
Traceback (most recent call last):
  File "/home/test/.venvs/aienv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/test/IdeaProjects/phidata/cookbook/mistral/app.py", line 13, in <module>
    from cookbook.mistral.mistral_assistant import get_mistral_assistant  # type: ignore
ModuleNotFoundError: No module named 'cookbook'
 

</p>
</details>

**Comment by ashpreetbedi** [comment]
@arw357 sorry about this, fix in this PR: https://github.com/phidatahq/phidata/pull/168

Please pull phidata from main or update the `cookbook/mistral/app.py`

change:
```
from cookbook.mistral.mistral_assistant import get_mistral_assistant  # type: ignore
```

to:
```
from mistral_assistant import get_mistral_assistant  # type: ignore
```
