### ISSUE TITLE
Is it possible to use custom api base url and key?

### ISSUE THREAD

**Issue by OmiiiDev** [phidatahq/phidata#181]

**Comment by ashpreetbedi** [comment]
@OmiiiDev absolutely, you can find it here for the `OpenAIChat` LLM: https://docs.phidata.com/llms/openai#:~:text=OpenAI%20organization-,base_url,-str

**Comment by ashpreetbedi** [comment]
Similarly all LLMs should support these classes, you can also use [`OpenAILike`](https://docs.phidata.com/llms/openai-like) if you'd like
