### ISSUE TITLE
RAG - data cleaning before adding Knowledge base document

### ISSUE THREAD

**Issue by mathieuchateau** [phidatahq/phidata#182]
When adding PDF to knowledge base, collecting text can end wrong, like this:

`Q U E L Q U E S A P P L I C A T I O N S E N A N A L Y S E L E X I C A L E E T L I N G U I S T I Q U E`

Other examples:

`dis.......quels sont`

`http : //www .cyberbr ic`

Currently, the only cleaning I can see is this in pgVector2.py:

`cleaned_content = document.content.replace("\x00", "\ufffd")`

I think we can increase quality of knowledge base by sanitizing data:

- Remove repeated characters
- Remove punctuation
- Remove single characters surrounded by space
- Using stopwords (like from nltk library)
- Lemmatize

I am quite new to the game for RAG, but we always do these text cleaning when doing embedding
I guess the worse part is that these garbages data count against maximum number of tokens, preventing to add more knowledge base articles.

**Comment by ashpreetbedi** [comment]
I completely agree @mathieuchateau

A current fix would be to load the `Documents` manually instead of using the `KnowledgeBase`, something like:

```
reader = PDFReader()
pdf_documents: List[Document] = reader.read(uploaded_file)
for doc in pdf_documents:
    doc.content = clean_content(doc.content)

assistant.knowledge_base.load_documents(pdf_documents, upsert=True)
```

You could also do it with a Website reader:

```
scraper = WebsiteReader(max_links=2, max_depth=1)
web_documents: List[Document] = scraper.read(input_url)
for doc in web_documents:
    doc.content = clean_content(doc.content)

assistant.knowledge_base.load_documents(web_documents, upsert=True)
```

[Example code](https://github.com/phidatahq/phidata/blob/main/cookbook/llms/groq/rag/app.py#L138-L141)

A long term approach would be to expose this as a parameter in the `KnowledgeBase` object, that accepts a "pre_process()" function, which runs on the content to clean it.

What do you think?

**Comment by e06084** [comment]
I'd recommend trying Dingo (https://github.com/DataEval/dingo) - a data quality evaluation tool that excels at preparing data for AI applications.
Dingo could solve your problems with:
- Built-in cleaning for repeated characters, misformatted text


It would fit well with the pre_process() approach suggested:

```python
from dingo.io import InputArgs
from dingo.exec import Executor

def clean_with_dingo(content: str) -> str:
    input_args = InputArgs(
        eval_group="pretrain",  # Comprehensive cleaning rules
        data=content,
        dataset="memory",
        data_format="plaintext"
    )
    executor = Executor.exec_map["local"](input_args)
    executor.execute()
    good_data = executor.get_good_info_list()
    return good_data[0].text if good_data else content

```
