### ISSUE TITLE
SQL issue 

### ISSUE THREAD

**Issue by Pythonllmcoder** [phidatahq/phidata#185]
StatementError: (builtins.ValueError) expected 4096 dimensions, not 0 [SQL: INSERT INTO ai.local_rag_documents_llama3 (id, name, meta_data, content, embedding, usage, content_hash) VALUES (%(id)s::VARCHAR, %(name)s::VARCHAR, %(meta_data)s::JSONB, %(content)s::VARCHAR, %(embedding)s, %(usage)s::JSONB, %(content_hash)s::VARCHAR) ON CONFLICT (id) DO UPDATE SET name = excluded.name, meta_data = excluded.meta_data, content = excluded.content, embedding = excluded.embedding, usage = excluded.usage, content_hash = excluded.content_hash] [parameters: [{}]]

**Comment by Joycoooi** [comment]
mee too.

**Comment by Joycoooi** [comment]
mee too. it can't upload pdf.

**Comment by ashpreetbedi** [comment]
@Pythonllmcoder is ollama running? Its required to generate the embeddings. 
The error is because the code couldnt generate the the embeddings. 

If `ollama pull llama3` or `ollama pull nomic-embed-text` doesnt solve this, please can you make sure the database is up?

Same with @Joycoooi, also feel free to hop on our discord https://phidata.link/discord

**Comment by ashpreetbedi** [comment]
@Joycoooi @Pythonllmcoder is this fixed on your side?

**Comment by ashpreetbedi** [comment]
@Joycoooi @Pythonllmcoder closing if okay ?

**Comment by Pythonllmcoder** [comment]
I am checking it with ollama. I will update you soon.

**Comment by ayofluxx** [comment]
I keep getting this error: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'svc-3482219c-a389-4079-b18b-d50662524e8a-shared-dml.aws-virginia-6.svc.singlestore.com' ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000))")

**Comment by ashpreetbedi** [comment]
please reopen if this persists
