### ISSUE TITLE
Couple questions...

### ISSUE THREAD

**Issue by OmiiiDev** [phidatahq/phidata#186]
So I have a couple questions about how this works:
1. Can I see a list of all the tools that are available and an example of how to use them?
2. Is there an example code or command on how to use the custom base url and api?
3. Does it support local models?

I have tried reading the documentation and didn't see many examples

**Comment by ashpreetbedi** [comment]
Hey @OmiiiDev:
1. Here are the [Toolkits](https://docs.phidata.com/tools/toolkits) we've documented till now. [Here is the full list](https://github.com/phidatahq/phidata/tree/main/phi/tools), but from code. We're working hard to document them all :)
2. Which LLM would you like an example for? [Here's how to use it with OpenAILike](https://docs.phidata.com/llms/openai-like)
3. We not only support, but love local models. [Here's the ollama cookbook](https://github.com/phidatahq/phidata/tree/main/cookbook/llms/ollama). You'll find many examples in there :)

We're working hard on updating the documentation so sorry for the inconvenience here :)
