### ISSUE TITLE
Documentation Issue: Bad Links

### ISSUE THREAD

**Issue by ahmadelmalah** [phidatahq/phidata#188]
On Toolkits page (https://docs.phidata.com/tools/toolkits) when I click on on any page like DuckDuckGo, Python, File or Shell, it redirects me back to introduction page (https://docs.phidata.com/introduction)

I tried from both Google Chrome and Microsoft Edge, and the problem appeared on both browsers

**Comment by ashpreetbedi** [comment]
thank you for the fix :)
