### ISSUE TITLE
Hermes not using tools

### ISSUE THREAD

**Issue by mlim1972** [phidatahq/phidata#195]
Version: 2.3.83

Using the example from https://docs.phidata.com/examples/llms/hermes2 I get the following:

<img width="989" alt="image" src="https://github.com/phidatahq/phidata/assets/1569407/8e37e918-f968-4b61-bc39-4f86c27473f3">

Using Ollama, I don't get the problem:
<img width="929" alt="image" src="https://github.com/phidatahq/phidata/assets/1569407/c3812be5-de30-409a-8303-2b86df1c3ad6">

**Comment by ashpreetbedi** [comment]
Thanks @mlim1972 we've seen some regression on the Hermes LLM so glad this is working with Ollama, will investigate further
