### ISSUE TITLE
Seeing this example is unclear, so

### ISSUE THREAD

**Issue by anan1213095357** [phidatahq/phidata#202]
Didn't you write your own code to execute this example based on the requirements? Why do I have to give him a file? Can I only ask him what's inside the CSV file?

from phi.assistant.python import PythonAssistant
from phi.file.local.csv import CsvFile

python_assistant = PythonAssistant(
    files=[
        CsvFile(
            path="https://phidata-public.s3.amazonaws.com/demo_data/IMDB-Movie-Data.csv",
            description="Contains information about movies from IMDB.",
        )
    ],
    pip_install=True,
    show_tool_calls=True,
)

python_assistant.print_response("What is the average rating of movies?", markdown=True)

**Comment by ashpreetbedi** [comment]
sorry @anan1213095357 i dont understand the question. we're asking the Assistant to answer the question by writing and running a python program
