### ISSUE TITLE
Deprecated function role messages in OpenAI LLM

### ISSUE THREAD

**Issue by zachschillaci27** [phidatahq/phidata#210]
It appears there are some instances of `function` role messages in the OpenAI LLM class, which are deprecated according to the official API reference available [here](https://platform.openai.com/docs/api-reference/chat/create#chat-create-messages) (see the `messages` field). These are mixed with the proper `tool` messages supported from the later versions of the OpenAI API.

For the modern implementation of function calling, you may refer to OpenAI's example [here](https://platform.openai.com/docs/guides/function-calling/parallel-function-calling).

See:
- https://github.com/phidatahq/phidata/blob/3481fcd955c7e003bd18cb6efd8c26aa7987557e/phi/llm/openai/chat.py#L192
- https://github.com/phidatahq/phidata/blob/3481fcd955c7e003bd18cb6efd8c26aa7987557e/phi/llm/openai/chat.py#L194
- https://github.com/phidatahq/phidata/blob/3481fcd955c7e003bd18cb6efd8c26aa7987557e/phi/llm/openai/chat.py#L203
- https://github.com/phidatahq/phidata/blob/3481fcd955c7e003bd18cb6efd8c26aa7987557e/phi/llm/openai/chat.py#L214
- https://github.com/phidatahq/phidata/blob/3481fcd955c7e003bd18cb6efd8c26aa7987557e/phi/llm/openai/chat.py#L225

**DISCLAIMER:** I do not currently use this package and only discovered this in my quick browsing of the codebase. Please let me know if I have misinterpreted something!

**Comment by ashpreetbedi** [comment]
@zachschillaci27 this is just for backward compatibility :) 

we're 100% using the new tool calls. Just have to keep as functions are not fully deprecated and some users are still using it :)
