### ISSUE TITLE
What is a run_id  and user_id

### ISSUE THREAD

**Issue by aurthurm** [phidatahq/phidata#212]
I have seen some instances where Assistant is given run_id and user_id. 

What are these and what are they used for? I have searched the docs and could not find an explanation

**Comment by ashpreetbedi** [comment]
@aurthurm the `run_id` and `user_id` are stored in your database table when you create storage for the assistant, so you can retrieve runs later by `run_id` or `user_id`. 

I'll make sure to add a full page in the docs walking through them in detail

**Comment by aurthurm** [comment]
So in this case a run is like a conversation thread that can be created with an assistant. 

From this we can say that:
1. multiple users can use the same assistant with each user having their own `user_id`
2. A user can initiate a conversation threat identified by a `run_id`
3. As such we can retrieve various conversations by a certain user.

Am i correct @ashpreetbedi

**Comment by ysolanky** [comment]
@aurthurm you got it exactly right!
