### ISSUE TITLE
unable to work on autorag in colab

### ISSUE THREAD

**Issue by bhanu866** [phidatahq/phidata#219]
can anyone please share colab code of autorag https://github.com/phidatahq/phidata/tree/main/cookbook/examples/auto_rag . i am unable to fix issue in google Colab

**Comment by ysolanky** [comment]
@bhanu866, there are a few issues to address:

- The Autonomous RAG example operates with a PgVector database hosted locally via Docker. While there are methods to connect your local server to a Google Colab notebook, I recommend using a cloud database like Qdrant or Pinecone for a smoother integration.
- Streamlit isn't natively compatible with Google Colab. While workarounds exist, the optimal experience is achieved by running Streamlit locally.

We will soon release new cookbooks demonstrating Phidata Assistants running on Jupyter Notebooks.
