### ISSUE TITLE
how to replace the default LLaMA3 model with my fine-tuned LLaMA3?

### ISSUE THREAD

**Issue by win4r** [phidatahq/phidata#220]
If I follow the steps outlined here "https://github.com/phidatahq/phidata/tree/main/cookbook/llms/ollama/rag", 
can I replace the default LLaMA3 model with my fine-tuned LLaMA3?

**Comment by ysolanky** [comment]
@win4r the tutorial you linked, demonstrates running llama3 using Ollama. You can use any model that's available on Ollama using Phidata by passing the model id as a param to the Ollama class 

Example: `assistant = Assistant(llm=Ollama(model="model_id"))`

 Can you share more details about your fine-tuned llama3 model? How are you hosting/running the model?

**Comment by win4r** [comment]
this is my model on huggingface:leo009/llama3

**Comment by chen-li1314** [comment]
> @win4r the tutorial you linked, demonstrates running llama3 using Ollama. You can use any model that's available on Ollama using Phidata by passing the model id as a param to the Ollama class
> 
> Example: `assistant = Assistant(llm=Ollama(model="model_id"))`
> 
> Can you share more details about your fine-tuned llama3 model? How are you hosting/running the model?

After replacing the fine-tuning model, I received an error ResponseError: model 'llama3' not found, try pulling it first

**Comment by chen-li1314** [comment]
> > @win4r the tutorial you linked, demonstrates running llama3 using Ollama. You can use any model that's available on Ollama using Phidata by passing the model id as a param to the Ollama class
> > Example: `assistant = Assistant(llm=Ollama(model="model_id"))`
> > Can you share more details about your fine-tuned llama3 model? How are you hosting/running the model?
> 
> After replacing the fine-tuning model, I received an error ResponseError: model 'llama3' not found, try pulling it first
![image](https://github.com/phidatahq/phidata/assets/127838017/33eab4a4-cb8e-4c00-adfe-6a547f7f8eb3)
![image](https://github.com/phidatahq/phidata/assets/127838017/a91733ef-fef0-418c-9337-872ce204b999)
My local olama will report an error
![image](https://github.com/phidatahq/phidata/assets/127838017/c8ca17e5-afcc-4948-bbd0-e03548ea231f)
What is API/embeddings
who can help me

**Comment by ju1987yetchung** [comment]
> > > @win4r the tutorial you linked, demonstrates running llama3 using Ollama. You can use any model that's available on Ollama using Phidata by passing the model id as a param to the Ollama class
> > > Example: 
> > > Can you share more details about your fine-tuned llama3 model? How are you hosting/running the model?`assistant = Assistant(llm=Ollama(model="model_id"))`
> > 
> > 
> > After replacing the fine-tuning model, I received an error ResponseError: model 'llama3' not found, try pulling it first
> > ![图像](https://private-user-images.githubusercontent.com/127838017/331162319-33eab4a4-cb8e-4c00-adfe-6a547f7f8eb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mzg5MzEsIm5iZiI6MTcxNjUzODYzMSwicGF0aCI6Ii8xMjc4MzgwMTcvMzMxMTYyMzE5LTMzZWFiNGE0LWNiOGUtNGMwMC1hZGZlLTZhNTQ3ZjdmOGViMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwODE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzI5MmNkMmE1NDkzNmUxZDkwOTdmMTJmYjA3MzU3N2VmNjhmMjk5Zjg4MDFhNjNkODI3OTJkYjI5NzY4YWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.959A5Rfk1mWqOadnnKKSscBqH1U1g4iw_rqYon3RZ9A)
> > ![图像](https://private-user-images.githubusercontent.com/127838017/331162487-a91733ef-fef0-418c-9337-872ce204b999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mzg5MzEsIm5iZiI6MTcxNjUzODYzMSwicGF0aCI6Ii8xMjc4MzgwMTcvMzMxMTYyNDg3LWE5MTczM2VmLWZlZjAtNDE4Yy05MzM3LTg3MmNlMjA0Yjk5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwODE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjdmOWM3MjE5YTNkOTcyNDNkZGJkNjk1Njk4MDU4MjVjZTc2OGI3ZmUwZGJhMzI5NDYwMWRhMmQ5NjE3ZWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.evxkCEKYWEtkVTs61X-upjfDdzG_AX7-_FCLHf9S46g)
> > My local olama will report an error
> > ![image](https://private-user-images.githubusercontent.com/127838017/331162751-c8ca17e5-afcc-4948-bbd0-e03548ea231f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mzg5MzEsIm5iZiI6MTcxNjUzODYzMSwicGF0aCI6Ii8xMjc4MzgwMTcvMzMxMTYyNzUxLWM4Y2ExN2U1LWFmY2MtNDk0OC1iYmQwLWUwMzU0OGVhMjMxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwODE3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDQzOTNhY2Y5OWFlYTA4NmIzNzU0ZmVkM2E5MjQ3OTc2Y2Y3YWY2ZWJkNjI5NTU0NWZiNmM5YTRlNzAzMzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fpDmiz6CH16jBtg-Rj9mnOYStFBgyRyG8DVvjXQHMAM)
> > What is API/embeddings
> > who can help me

I have same problem. mark this issue and wait an answer.
