### ISSUE TITLE
Need support for PDFs with images

### ISSUE THREAD

**Issue by sridharaiyer** [phidatahq/phidata#240]
[Uploading Fake-Police-Report-HighRes.pdf…]()
I want to read from a PDF that contains text inside an image. See attached. I am able to do this using [Langchain](https://python.langchain.com/v0.1/docs/modules/data_connection/document_loaders/pdf/) by installing `pip install rapidocr-onnxruntime`. I want the `from phi.document.reader.pdf import PDFReader` PDFReader class to support this.

Any suggestions for me to be able to do RAG with PDFS with images, while this request is being implemented?

**Comment by ashpreetbedi** [comment]
@sridharaiyer agree this is critical @ysolanky @jacobweiss2305 any takers?

**Comment by ashpreetbedi** [comment]
@sridharaiyer mind sharing a good PDF to test this with?

**Comment by ysolanky** [comment]
@sridharaiyer The PDF Image reader is ready. It would be great it you could share an ideal pdf for your use case so that we can test further before releasing :)

**Comment by llegomark** [comment]
@sridharaiyer Good day, team phidata! Thank you for your prompt response and willingness to address this critical feature request. I appreciate your dedication to continuously improving the library.

To aid in your testing, I would like to share the following PDF files that contain a mix of text and images:
1. [](https://www.deped.gov.ph/wp-content/uploads/DO_s2024_005.pdf)
2. [](https://www.deped.gov.ph/wp-content/uploads/DO_s2024_002.pdf)

These PDFs are representative of the types of documents I frequently work with, and having the ability to extract text from images within PDFs would greatly enhance my workflow.

I have been using phidata for my personal projects and have found it to be an invaluable tool. Additionally, I have been following the progress of the library and the insightful video demos led by Sir @ashpreetbedi on Twitter.

Thank you once again for your efforts in making phidata an even more powerful and versatile library. I look forward to testing the PDF Image reader feature once it is released.

**Comment by ashpreetbedi** [comment]
@sridharaiyer The `PDFImageReader` is now live in v2.4.8

We can import it using `from phi.document.reader.pdf import PDFImageReader`

@ysolanky please add some docs to help :)

@llegomark thank you for sharing the PDFs and your help with the product. 

we appreciate your help with this so much

**Comment by sridharaiyer** [comment]
Thanks a lot team!! The PDF with an image containing text is indeed being read properly. So I am closing this ticket.

However, I have another question in regards to the knowledge base strategy. I will open another thread.
Thanks, once again!!
