### ISSUE TITLE
[Feature] Adding `ChatGPT Like Memory`

### ISSUE THREAD

**Issue by mahimairaja** [phidatahq/phidata#252]
Recently, OpenAI announced this [ChatGPT Memory](https://www.wired.com/story/how-to-use-chatgpt-memory-feature/) feature. That the app can remember the important keypoints from our conversation. Instead of keeping track of the entire conversation history, how about digesting and storing the important key leads to the vectorDB? Then retrieving it along with the knowledge?

-- 

Looking forward to listen to the opinions and contributing

**Comment by ashpreetbedi** [comment]
Awesome, great one @mahimairaja! the team is working on this :)

**Comment by ashpreetbedi** [comment]
cc: @ysolanky @jacobweiss2305 @anuragts
