### ISSUE TITLE
Assistant's LLM tools list contains duplicates causing tools list limit OpenAI error

### ISSUE THREAD

**Issue by nate-mar** [phidatahq/phidata#254]
Assistant tools are [updated](https://github.com/phidatahq/phidata/blob/main/phi/assistant/assistant.py#L280-L299) after every [run](https://github.com/phidatahq/phidata/blob/main/phi/assistant/assistant.py#L775). When they are updated, tools are appended to the llm's list of tools, but it doesn't appear that the tools are deduplicated before they are appended to the list. The result is that if there are enough runs performed, then the list of tools will exceed the allowed number of tools in an LLM request. Specifically for OpenAI GPT-4 that limit is 128. 

When I ran the LLM OS and had a chat with around 8 interactions, I received this OpenAI error:

```
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'tools': array too long. Expected an array with maximum length 128, but got an array with length 135 instead.", 'type': 'invalid_request_error', 'param': 'tools', 'code': 'array_above_max_length'}}
```

I manually logged the tools argument and could see in the console that the list simply grows longer after every exchange, and that the list contains duplicate tools.  To reproduce, you can load up the LLM OS cookbook, and have a conversation with the LLM with roughly 8  exchanges.

Happy to take a pass at addressing this (once someone confirms)! Looks like it will have to involve doing a full list check, unless the tools attribute is replaced with a Dict perhaps (the llm functions attribute look like a Dict though).

**Comment by nexxeln** [comment]
i also faced this issue

**Comment by nexxeln** [comment]
i think a simple deduplication of the list should work.

```py
self.llm.tools = list({tool.name: tool for tool in self.llm.tools}.values())
```

but using a dict might be better

**Comment by jacobweiss2305** [comment]
@ysolanky and I are working on a fix.

**Comment by nate-mar** [comment]
@jacobweiss2305 awesome -- happy to help out in any way

**Comment by anhuibl** [comment]
i also faced this issue, please fix it. Thanks so much!

**Comment by sigren** [comment]
please!

**Comment by ysolanky** [comment]
PR is already out for this issue. It will be fixed in the next release 🙂

**Comment by nate-mar** [comment]
Fixed via https://github.com/phidatahq/phidata/pull/973
