### ISSUE TITLE
mypy check

### ISSUE THREAD

**Issue by hansipie** [phidatahq/phidata#258]
Hello

According to the 'mypy' check:
phi\assistant\openai\assistant.py:122: error: "Assistant" has no attribute "file_ids"  [attr-defined]
phi\assistant\openai\run.py:131: error: "Run" has no attribute "file_ids"  [attr-defined]

Indeed, I believe the OpenAIAssistan API has changed, but i didn't find any proof. However, those attributes are no longer present...
https://platform.openai.com/docs/api-reference/runs/object
https://platform.openai.com/docs/api-reference/assistants/object

I'll make a PR asap, but if you are faster then me go ahead :)

PS: This project is awesome ! Thank you :)

**Comment by ysolanky** [comment]
@hansipie You are right. OpenAI has made some changes to their package resulting in these mypy errors. Feel free to make a PR :)
