### ISSUE TITLE
"please list all the questions I asked in this chat" - throws error in get_chat_history

### ISSUE THREAD

**Issue by kosiew** [phidatahq/phidata#259]
<img width="826" alt="image" src="https://github.com/phidatahq/phidata/assets/29057562/a1db1ebf-4f12-42fa-a40b-b12579c3536c">

Steps to reproduce:

1. `python cookbook/assistants/pdf_assistant.py --new`
2. Ask "what goes well with pad thai", wait for reply to complete
3. Ask "I like soups. can you suggest 3 more soups", wait for reply to complete
4. "please list all the questions I asked in this chat"

**Comment by jacobweiss2305** [comment]
I was able to recreate. Working on it...

**Comment by jacobweiss2305** [comment]
https://github.com/phidatahq/phidata/pull/300
