### ISSUE TITLE
Replace the locally fine tuned model

### ISSUE THREAD

**Issue by chen0321-max** [phidatahq/phidata#261]
When I tried rag related experiments, I encountered some issues when replacing llama3 with my locally fine tuned large model, Ollama_ Types ResponseError: model 'llama3' not found, try pulling it first, but I have already changed the name,
Def get_rag_sssistant（
Llm_model: str="llama3: install",
Embeddings model: str="nic embedded text",
User_id: Optional [str]=None,
Run_id: Optional [str]=None,
Debug_mode: bool=True,
）->Assistant:
I don't understand why this is happening
![708f6c2515082971d9f9c1d8749548b](https://github.com/phidatahq/phidata/assets/127838017/11377c41-23f7-4a7b-83e9-a0ec33388af0)
When I changed it to the default llama3, it still reported an error. I want to know how to call olama in the source code and if it is possible to change its default location. I feel that the problem lies here

**Comment by jacobweiss2305** [comment]
@chen-li1314 here is how to set an ollama model with an assistant. Assuming you pull and run the model using Ollama cli.
https://docs.phidata.com/llms/ollama

Let me know if you tried this.

Also we are on discord which has a Ollama experts in the channel who can help:
https://discord.com/invite/4MtYHHrgA8

**Comment by jacobweiss2305** [comment]
Try this `ollama pull llama3`

**Comment by chen-li1314** [comment]
> Try this `ollama pull llama3`

Thank you for your reply. I have found that Ollama pull llama3 can solve this problem, but strangely, I don't even need to change the name of the model: llama: install (the name of the local large model I previously modified). So how should I use the locally fine tuned model? Since setting the name doesn't work

**Comment by chen-li1314** [comment]
> @chen-li1314 here is how to set an ollama model with an assistant. Assuming you pull and run the model using Ollama cli. https://docs.phidata.com/llms/ollama
> 
> Let me know if you tried this.
> 
> Also we are on discord which has a Ollama experts in the channel who can help: https://discord.com/invite/4MtYHHrgA8

I will have  a try
