### ISSUE TITLE
[tool.poetry] section not found in pyproject.toml

### ISSUE THREAD

**Issue by alonsoir** [phidatahq/phidata#263]
Hi, i have tried to run poetry shell to create the virtual enviroment and i got this:

(venv) ┌<▸> ~/g/phidata 
└➤ poetry shell                    

[tool.poetry] section not found in /Users/aironman/git/phidata/pyproject.toml
(venv) ┌<▪> ~/g/phidata 
└➤ poetry update

[tool.poetry] section not found in /Users/aironman/git/phidata/pyproject.toml
(venv) ┌<▪> ~/g/phidata 
└➤ pip install --upgrade poetry
Collecting poetry
  Downloading poetry-1.8.3-py3-none-any.whl.metadata (6.8 kB)
Collecting build<2.0.0,>=1.0.3 (from poetry)
  Using cached build-1.2.1-py3-none-any.whl.metadata (4.3 kB)
Collecting cachecontrol<0.15.0,>=0.14.0 (from cachecontrol[filecache]<0.15.0,>=0.14.0->poetry)
  Using cached cachecontrol-0.14.0-py3-none-any.whl.metadata (3.1 kB)
Collecting cleo<3.0.0,>=2.1.0 (from poetry)
  Using cached cleo-2.1.0-py3-none-any.whl.metadata (12 kB)
Collecting crashtest<0.5.0,>=0.4.1 (from poetry)
  Using cached crashtest-0.4.1-py3-none-any.whl.metadata (1.1 kB)
Collecting dulwich<0.22.0,>=0.21.2 (from poetry)
  Using cached dulwich-0.21.7-cp311-cp311-macosx_10_9_x86_64.whl.metadata (4.3 kB)
Collecting fastjsonschema<3.0.0,>=2.18.0 (from poetry)
  Using cached fastjsonschema-2.19.1-py3-none-any.whl.metadata (2.1 kB)
Collecting installer<0.8.0,>=0.7.0 (from poetry)
  Using cached installer-0.7.0-py3-none-any.whl.metadata (936 bytes)
Collecting keyring<25.0.0,>=24.0.0 (from poetry)
  Using cached keyring-24.3.1-py3-none-any.whl.metadata (20 kB)
Collecting packaging>=23.1 (from poetry)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting pexpect<5.0.0,>=4.7.0 (from poetry)
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting pkginfo<2.0,>=1.10 (from poetry)
  Using cached pkginfo-1.10.0-py3-none-any.whl.metadata (11 kB)
Collecting platformdirs<5,>=3.0.0 (from poetry)
  Downloading platformdirs-4.2.2-py3-none-any.whl.metadata (11 kB)
Collecting poetry-core==1.9.0 (from poetry)
  Using cached poetry_core-1.9.0-py3-none-any.whl.metadata (3.5 kB)
Collecting poetry-plugin-export<2.0.0,>=1.6.0 (from poetry)
  Downloading poetry_plugin_export-1.8.0-py3-none-any.whl.metadata (2.8 kB)
Collecting pyproject-hooks<2.0.0,>=1.0.0 (from poetry)
  Using cached pyproject_hooks-1.1.0-py3-none-any.whl.metadata (1.3 kB)
Collecting requests<3.0,>=2.26 (from poetry)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting requests-toolbelt<2.0.0,>=1.0.0 (from poetry)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: shellingham<2.0,>=1.5 in ./venv/lib/python3.11/site-packages (from poetry) (1.5.4)
Collecting tomlkit<1.0.0,>=0.11.4 (from poetry)
  Downloading tomlkit-0.12.5-py3-none-any.whl.metadata (2.7 kB)
Collecting trove-classifiers>=2022.5.19 (from poetry)
  Using cached trove_classifiers-2024.4.10-py3-none-any.whl.metadata (2.2 kB)
Collecting virtualenv<21.0.0,>=20.23.0 (from poetry)
  Downloading virtualenv-20.26.2-py3-none-any.whl.metadata (4.4 kB)
Collecting xattr<2.0.0,>=1.0.0 (from poetry)
  Using cached xattr-1.1.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (3.8 kB)
Collecting msgpack<2.0.0,>=0.5.2 (from cachecontrol<0.15.0,>=0.14.0->cachecontrol[filecache]<0.15.0,>=0.14.0->poetry)
  Using cached msgpack-1.0.8-cp311-cp311-macosx_10_9_x86_64.whl.metadata (9.1 kB)
Collecting filelock>=3.8.0 (from cachecontrol[filecache]<0.15.0,>=0.14.0->poetry)
  Using cached filelock-3.14.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rapidfuzz<4.0.0,>=3.0.0 (from cleo<3.0.0,>=2.1.0->poetry)
  Downloading rapidfuzz-3.9.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (11 kB)
Collecting urllib3>=1.25 (from dulwich<0.22.0,>=0.21.2->poetry)
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting jaraco.classes (from keyring<25.0.0,>=24.0.0->poetry)
  Using cached jaraco.classes-3.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting importlib-metadata>=4.11.4 (from keyring<25.0.0,>=24.0.0->poetry)
  Using cached importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
Collecting ptyprocess>=0.5 (from pexpect<5.0.0,>=4.7.0->poetry)
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0,>=2.26->poetry)
  Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (33 kB)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.11/site-packages (from requests<3.0,>=2.26->poetry) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.11/site-packages (from requests<3.0,>=2.26->poetry) (2024.2.2)
Collecting distlib<1,>=0.3.7 (from virtualenv<21.0.0,>=20.23.0->poetry)
  Using cached distlib-0.3.8-py2.py3-none-any.whl.metadata (5.1 kB)
Collecting cffi>=1.16.0 (from xattr<2.0.0,>=1.0.0->poetry)
  Using cached cffi-1.16.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.16.0->xattr<2.0.0,>=1.0.0->poetry)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting zipp>=0.5 (from importlib-metadata>=4.11.4->keyring<25.0.0,>=24.0.0->poetry)
  Downloading zipp-3.18.2-py3-none-any.whl.metadata (3.5 kB)
Collecting more-itertools (from jaraco.classes->keyring<25.0.0,>=24.0.0->poetry)
  Downloading more_itertools-10.2.0-py3-none-any.whl.metadata (34 kB)
Downloading poetry-1.8.3-py3-none-any.whl (249 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 249.9/249.9 kB 3.7 MB/s eta 0:00:00
Using cached poetry_core-1.9.0-py3-none-any.whl (309 kB)
Using cached build-1.2.1-py3-none-any.whl (21 kB)
Using cached cachecontrol-0.14.0-py3-none-any.whl (22 kB)
Using cached cleo-2.1.0-py3-none-any.whl (78 kB)
Using cached crashtest-0.4.1-py3-none-any.whl (7.6 kB)
Using cached dulwich-0.21.7-cp311-cp311-macosx_10_9_x86_64.whl (475 kB)
Using cached fastjsonschema-2.19.1-py3-none-any.whl (23 kB)
Using cached installer-0.7.0-py3-none-any.whl (453 kB)
Using cached keyring-24.3.1-py3-none-any.whl (38 kB)
Using cached packaging-24.0-py3-none-any.whl (53 kB)
Using cached pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
Using cached pkginfo-1.10.0-py3-none-any.whl (30 kB)
Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
Downloading poetry_plugin_export-1.8.0-py3-none-any.whl (10 kB)
Using cached pyproject_hooks-1.1.0-py3-none-any.whl (9.2 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading tomlkit-0.12.5-py3-none-any.whl (37 kB)
Using cached trove_classifiers-2024.4.10-py3-none-any.whl (13 kB)
Downloading virtualenv-20.26.2-py3-none-any.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 8.8 MB/s eta 0:00:00
Using cached xattr-1.1.0-cp311-cp311-macosx_10_9_x86_64.whl (18 kB)
Using cached cffi-1.16.0-cp311-cp311-macosx_10_9_x86_64.whl (182 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_10_9_x86_64.whl (121 kB)
Using cached distlib-0.3.8-py2.py3-none-any.whl (468 kB)
Using cached filelock-3.14.0-py3-none-any.whl (12 kB)
Using cached importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Using cached msgpack-1.0.8-cp311-cp311-macosx_10_9_x86_64.whl (87 kB)
Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Downloading rapidfuzz-3.9.0-cp311-cp311-macosx_10_9_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 5.3 MB/s eta 0:00:00
Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Using cached jaraco.classes-3.4.0-py3-none-any.whl (6.8 kB)
Downloading zipp-3.18.2-py3-none-any.whl (8.3 kB)
Downloading more_itertools-10.2.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 1.8 MB/s eta 0:00:00
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Installing collected packages: trove-classifiers, ptyprocess, fastjsonschema, distlib, zipp, urllib3, tomlkit, rapidfuzz, pyproject-hooks, pycparser, poetry-core, platformdirs, pkginfo, pexpect, packaging, msgpack, more-itertools, installer, filelock, crashtest, charset-normalizer, virtualenv, requests, jaraco.classes, importlib-metadata, dulwich, cleo, cffi, build, xattr, requests-toolbelt, keyring, cachecontrol, poetry-plugin-export, poetry
Successfully installed build-1.2.1 cachecontrol-0.14.0 cffi-1.16.0 charset-normalizer-3.3.2 cleo-2.1.0 crashtest-0.4.1 distlib-0.3.8 dulwich-0.21.7 fastjsonschema-2.19.1 filelock-3.14.0 importlib-metadata-7.1.0 installer-0.7.0 jaraco.classes-3.4.0 keyring-24.3.1 more-itertools-10.2.0 msgpack-1.0.8 packaging-24.0 pexpect-4.9.0 pkginfo-1.10.0 platformdirs-4.2.2 poetry-1.8.3 poetry-core-1.9.0 poetry-plugin-export-1.8.0 ptyprocess-0.7.0 pycparser-2.22 pyproject-hooks-1.1.0 rapidfuzz-3.9.0 requests-2.31.0 requests-toolbelt-1.0.0 tomlkit-0.12.5 trove-classifiers-2024.4.10 urllib3-2.2.1 virtualenv-20.26.2 xattr-1.1.0 zipp-3.18.2

(venv) ┌<▸> ~/g/phidata 
└➤ poetry shell                

[tool.poetry] section not found in /Users/aironman/git/phidata/pyproject.toml

(venv) ┌<▸> ~/g/phidata 
└➤ pip install -r requirements.txt
Requirement already satisfied: annotated-types==0.6.0 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.6.0)
Requirement already satisfied: anyio==4.3.0 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (4.3.0)
Requirement already satisfied: certifi==2024.2.2 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (2024.2.2)
Requirement already satisfied: click==8.1.7 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (8.1.7)
Requirement already satisfied: exceptiongroup==1.2.0 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (1.2.0)
Requirement already satisfied: gitdb==4.0.11 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (4.0.11)
Requirement already satisfied: gitpython==3.1.43 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 13)) (3.1.43)
Requirement already satisfied: h11==0.14.0 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 14)) (0.14.0)
Requirement already satisfied: httpcore==1.0.5 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (1.0.5)
Requirement already satisfied: httpx==0.27.0 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 16)) (0.27.0)
Requirement already satisfied: idna==3.7 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 17)) (3.7)
Requirement already satisfied: markdown-it-py==3.0.0 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 18)) (3.0.0)
Requirement already satisfied: mdurl==0.1.2 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 19)) (0.1.2)
Requirement already satisfied: pydantic==2.7.0 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 20)) (2.7.0)
Requirement already satisfied: pydantic-core==2.18.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 21)) (2.18.1)
Requirement already satisfied: pydantic-settings==2.2.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 22)) (2.2.1)
Requirement already satisfied: pygments==2.17.2 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 23)) (2.17.2)
Requirement already satisfied: python-dotenv==1.0.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 24)) (1.0.1)
Requirement already satisfied: pyyaml==6.0.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 25)) (6.0.1)
Requirement already satisfied: rich==13.7.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 26)) (13.7.1)
Requirement already satisfied: shellingham==1.5.4 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 27)) (1.5.4)
Requirement already satisfied: smmap==5.0.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 28)) (5.0.1)
Requirement already satisfied: sniffio==1.3.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 29)) (1.3.1)
Requirement already satisfied: tomli==2.0.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 30)) (2.0.1)
Requirement already satisfied: typer==0.12.3 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 31)) (0.12.3)
Requirement already satisfied: typing-extensions==4.11.0 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 32)) (4.11.0)
(venv) ┌<▸> ~/g/phidata 
└➤ poetry install                 

[tool.poetry] section not found in /Users/aironman/git/phidata/pyproject.toml
(venv) ┌<▪> ~/g/phidata 
└➤ 

So, i am confused, are you not using poetry de work with dependencies?

Thank you

**Comment by jacobweiss2305** [comment]
@alonsoir good call out. Are you contributing to the repo? If so can you use these requirements instructions:
https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md

Or are you trying to build an Assistant?

**Comment by jacobweiss2305** [comment]
I primarily use the scripts to setup dependancies:
https://github.com/phidatahq/phidata/tree/main/scripts

**Comment by alonsoir** [comment]
> @alonsoir good call out. Are you contributing to the repo? If so can you use these requirements instructions: https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md
> 
> Or are you trying to build an Assistant?

Right now i am trying to build an assistant. I would prefer to do it the poetry way instead of pip way.

**Comment by alonsoir** [comment]
> Hey @alonsoir
> 
> Did you init the poetry?
> 
> ```shell
> $ poetry init
> 
> $ poetry lock
> 
> $ poetry shell
> ```

```
(venv) ┌<▪> ~/g/phidata 
└➤ poetry init 
A pyproject.toml file with a defined build-system already exists.
(venv) ┌<▪> ~/g/phidata 
└➤ poetry lock            

[tool.poetry] section not found in /Users/aironman/git/phidata/pyproject.toml
(venv) ┌<▪> ~/g/phidata 
└➤ poetry shell

[tool.poetry] section not found in /Users/aironman/git/phidata/pyproject.toml
```

**Comment by alonsoir** [comment]
> I see.
> 
> Did you try validating the `pyproject.tomly` by using
> 
> ```shell
> $ poetry check
> ```

(venv) ┌<▸> ~/g/phidata 
└➤ poetry check            

[tool.poetry] section not found in /Users/aironman/git/phidata/pyproject.toml
