### ISSUE TITLE
Knowledge base without pgvector

### ISSUE THREAD

**Issue by sridharaiyer** [phidatahq/phidata#303]
Hello team. Is there a way to use phidata as a RAG, where the vectors are stored in a vectordb such as chroma, dynamically created in the same directory, when I run the application using Streamlit?

Reason: 
1. Many a times, my consumers won't prefer spinning up a postgres docker container
2. What if I want to deploy my streamlit app?
3. If the postgres is not cleared of its old knowledge base, the LLM can get confused when I keep adding more documents.

**Comment by jacobweiss2305** [comment]
@ysolanky is currently working on chromadb integration. We are close to getting this added.

Take a look at these docs and let me know if it helps:
https://docs.phidata.com/assistants/knowledge
https://docs.phidata.com/examples/assistants/rag

**Comment by jacobweiss2305** [comment]
@sridharaiyer , we are close to adding chromadb (S/O @ysolanky). Within the week it should be out.

We have current integrations with Pinecone, Qdrant, Lancedb, Singlestore,

**Comment by jacobweiss2305** [comment]
@sridharaiyer checkout lancedb its dynamic and can be deployed anywhere

# Lancedb Assistant

### 1. Create a virtual environment
```shell
python3 -m venv ~/.venvs/aienv
source ~/.venvs/aienv/bin/activate
```

### 2. Install libraries
```shell
pip install -U lancedb pypdf pandas openai phidata
```

### 3. Run Assistant
```shell
python cookbook/integrations/lancedb/assistant.py
```

**Comment by sridharaiyer** [comment]
Thanks for the guidance. Closing this ticket.
