### ISSUE TITLE
YFinanceTools().get_historical_stock_prices returns only one datapoint

### ISSUE THREAD

**Issue by rawmean** [phidatahq/phidata#307]
To test, do this and observe that only one datapoint is returns (instead of the default which should be daily for one month). I also tried different values for `period` and `interval` parameters.

```
data = YFinanceTools().get_historical_stock_prices(symbol="NVDA")  
print(data)
```

**Comment by rawmean** [comment]
#308

**Comment by ysolanky** [comment]
Thanks for the PR @rawmean. Sometimes the LLM would request historical data across a long interval (5 years+) exceeding the context window of some of the smaller models. But happy to test this and set some checks to avoid that.

**Comment by rawmean** [comment]
Thanks. 5+ years interval may not be necessarily large if the period is set to 1mo as an example. If you insist on putting a check, maybe the check should be on number of samples and not the "interval".
