### ISSUE TITLE
Add LanceDB knowledge base

### ISSUE THREAD

**Issue by ashpreetbedi** [phidatahq/phidata#59]
- **Task:** Add LanceDb as a vector store so it can be used as a knowledge base
- [How to add a new vector database](https://github.com/phidatahq/phidata/blob/main/CONTRIBUTING.md#adding-a-new-vector-database)
- [Other vector dbs for example](https://github.com/phidatahq/phidata/tree/main/phi/vectordb)
- [Example cookbook to create an test the integration](https://github.com/phidatahq/phidata/tree/main/cookbook/singlestore)

**Comment by ashpreetbedi** [comment]
@AkshatHotCode just added more information, happy to help

**Comment by akashAD98** [comment]
@ashpreetbedi  both are only for llm not for vectordb .you  copied  same thing double
![image](https://github.com/phidatahq/phidata/assets/62583018/8da0f76a-6dd9-41ca-8721-197c504c63d0)

**Comment by ashpreetbedi** [comment]
@akashAD98 just updated :)

**Comment by visdalal** [comment]
## Important Discovery: Vendor Directories are Git Submodule Pointers

### Current Setup
- `src/LightRAG` and `src/discord.py` are tracked as **git submodule pointers** (mode 160000)
- They point to specific commits but the actual code is not committed to the main repo
- This is why changes in these directories don't get committed - Git only tracks the commit pointer
- There's no `.gitmodules` file, which is unusual but works

### Evidence
```bash
$ git ls-tree HEAD src/ | grep -E "LightRAG|discord"
160000 commit 2bc6938b6a5f2877874e4450d3cf615ab0611d13	src/LightRAG
160000 commit 26855160f8a8f0dfade609cce6b1bc97f8b8fa14	src/discord.py
```

The "160000" mode indicates these are submodule pointers.

## Options for Handling Agno

### Option 1: Convert Agno to Submodule Pointer (Match Current Pattern)
```bash
# Add agno as a submodule pointer
cd /Users/vishaldalal/async_agents
git rm -rf src/agno  # Remove if already tracked as regular directory
git add src/agno      # Add as submodule pointer
git commit -m "Track agno as submodule pointer"
```

### Option 2: Proper Submodules with .gitmodules
```bash
# Remove existing entries
git rm -r --cached src/LightRAG src/discord.py src/agno

# Add as proper submodules
git submodule add https://github.com/visdalal/LightRAG.git src/LightRAG
git submodule add https://github.com/visdalal/discord.py.git src/discord.py
git submodule add https://github.com/visdalal/agno.git src/agno  # Need to create fork first

# This creates .gitmodules file
```

### Option 3: Keep Current Pattern, Add to .gitignore
Even though they're submodule pointers, adding to .gitignore prevents accidental changes:
```gitignore
# Vendor submodules - changes not tracked
src/agno/
src/LightRAG/
src/discord.py/
```

### Option 4: Use git update-index (Local Only)
```bash
# Tell git to ignore changes in these directories
git update-index --skip-worktree src/LightRAG
git update-index --skip-worktree src/discord.py
git update-index --skip-worktree src/agno
```

## Recommendation

**Option 1** - Match the current pattern:
1. Ensure agno is tracked as a submodule pointer like LightRAG and discord.py
2. This prevents any code changes from being committed
3. Only the commit pointer is tracked

**For CI/CD Fix**:
- The relative paths in pyproject.toml should still work
- Or we can modify the workflow to handle missing directories

This explains why no vendor code gets committed despite not being in .gitignore\!
