### ISSUE TITLE
OpenAI assistant inconsistent with Assistant

### ISSUE THREAD

**Issue by adieyal** [phidatahq/phidata#68]
Not sure if this is by design, but the OpenAIAssistant doesn't accept Functions as tools which the regular assistant does.

https://github.com/phidatahq/phidata/blob/4ee0982f5ee6d5190bf71a482e9ff4ccfe252722/phi/assistant/openai/assistant.py#L41

https://github.com/phidatahq/phidata/blob/4ee0982f5ee6d5190bf71a482e9ff4ccfe252722/phi/assistant/assistant.py#L71

**Comment by ashpreetbedi** [comment]
Agree, will fix

**Comment by ashpreetbedi** [comment]
Fix released with v2.3.9
