### ISSUE TITLE
Add skypilot as underlaying Infrastructure provider

### ISSUE THREAD

**Issue by chymian** [phidatahq/phidata#80]
I'm just exploring this very promising project.

IMHO, [skypilot](https://github.com/skypilot-org/skypilot) would be the perfect match for phidata & running ai_apps.

> About
SkyPilot: Run LLMs, AI, and Batch jobs on any cloud. Get maximum savings, highest GPU availability, and managed execution—all with a simple interface.

basically, after writing a short deployment (yaml) once, a app can be run on any configured cloud, even local on k8s.
skypilot searches for the actual cheapest prices for the configured resources and starts the app, including loadbalancer, scaling, tunneles, etc… 

edit: fixed typos

**Comment by ashpreetbedi** [comment]
@chymian Great call :) let me look into this
