### ISSUE TITLE
Wikipedia KnowledgeBase Cookbook

### ISSUE THREAD

**Issue by ashpreetbedi** [phidatahq/phidata#91]
Create a cookbook: `cookbook/knowledge/wikipedia.py` showcasing how to use the [WikipediaKnowledgeBase](https://docs.phidata.com/blocks/kb/wikipedia)

**Comment by justinqcai** [comment]
Hi @ashpreetbedi , I've created a PR to address this issue, commenting here for visibility.

**Comment by ashpreetbedi** [comment]
Thank you @justinqcai !! just merged and appreciate your contribution :)
