### ISSUE TITLE
PDF KnowledgeBase Cookbook

### ISSUE THREAD

**Issue by ashpreetbedi** [phidatahq/phidata#94]
Create a cookbook: `cookbook/knowledge/pdf.py` showcasing how to use the [PDFKnowledgeBase](https://docs.phidata.com/blocks/kb/pdf)

**Comment by mjcarbonell** [comment]
Hi Ashpreet! I've gone ahead and made a pull request for you and your team to check out. Let me know if there are any issues with it or if you need more done in this area of the project! Pull request is here: https://github.com/phidatahq/phidata/pull/113

**Comment by ashpreetbedi** [comment]
Thank you @mjcarbonell !!! 🚀 🚢
