### ISSUE TITLE
Using Gemini from Google AI Studio

### ISSUE THREAD

**Issue by LuciAkirami** [phidatahq/phidata#952]
I wish to use the Gemini model through the free API Key provided by the Google AI Studio. But I could not find a way to do so in phidata. The existing Gemini Integration requires me go through the GCP Vertex AI process. So is there such a way, where I could work with Gemini with the free API key in the existing phidata library?

**Comment by jacobweiss2305** [comment]
Taking a look!

**Comment by sigren** [comment]
Please!

**Comment by FriendlyUser** [comment]
Also interested in this.

**Comment by alvinchiang1121** [comment]
Do we have an answer yet?

**Comment by ysolanky** [comment]
Really sorry about the delay on this. Will have an update by the next of next week at the latest

**Comment by ysolanky** [comment]
A PR for Gemini using Google AI studio is out. Everyone is welcome to test: https://github.com/phidatahq/phidata/pull/1044/files#diff-fb9f409a48a84801a4a5202749a6868766bec55aa1c4fad095ef42bcd88a8336

**Comment by sigren** [comment]
gemini-1.5-pro returns JSON with control characters; should deal with this in a way that's similar to Anthropic models by being less strict in JSON parsing:

`WARNING  Failed to validate response: 1 validation error for ExplainAnswer
           Invalid JSON: control character (\u0000-\u001F) found while parsing a string at line 4 column 0 [type=json_invalid, input_value='{\n
         "answer": "C",\n  "..."string"\n    }\n  }\n}', input_type=str]`

**Comment by ysolanky** [comment]
@sigren can you please share the steps to recreate this warning?

**Comment by sigren** [comment]
@ysolanky my particular example is very complicated with tool use, RAG and chain of thoughts.
Quite often structured (JSON) response from models by Anthropic and Gemini contain control characters. This issue was fixed in "instructor" library by parsing JSON string in non-strict mode.
