### ISSUE TITLE
we could also use a  docker compose file 

### ISSUE THREAD

**Issue by OscarAgreda** [phidatahq/phidata#963]
we can also use a docker compose file where we can see the data on the database

`version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    mem_limit: 512m
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5050:80
    networks:
      - backend
    depends_on:
      - pgvector
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  pgvector:
    image: phidata/pgvector:16
    container_name: pgvector # use this server name in pgadmin
    environment:
      - POSTGRES_DB=ai # use this db name while connecting to pgadmin
      - POSTGRES_USER=ai # use this user name while connecting to pgadmin
      - POSTGRES_PASSWORD=ai # use this password name while connecting to pgadmin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data 
    ports:
      - 5532:5432
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ai
      interval: 10s
      timeout: 5s
      retries: 5

  portainer:
    image: portainer/portainer-ce
    mem_limit: 256m
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    networks:
      - backend
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password1234567890
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  backend:
    driver: bridge

volumes:
  portainer_data:
    driver: local
  pgvolume: 
    driver: local
  pgadmin_data:
    driver: local
  nosqlclient_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local`

**Comment by ysolanky** [comment]
@OscarAgreda this is great feedback. I am going to look into using portainer+pgadmin. Thanks!
