### ISSUE TITLE
why the team member run in none stream mode

### ISSUE THREAD

**Issue by chivalry1314** [phidatahq/phidata#970]
I found when assistant as team member, it must run in no stream mode, could someone explain this. because I need LLM run in stream mode. I want to make sure this change cannot affect other functions. 
![微信图片_20240521111840](https://github.com/phidatahq/phidata/assets/16643409/f5ede5ff-3939-47da-b014-7cdf6841888c)

**Comment by jacobweiss2305** [comment]
This is for delegating tasks. We decided not to stream results during the "delegation" stage.

However, you can still have the customer facing agent stream.
