### ISSUE TITLE
2.4.13 -> knowledge/pdf file does not contain PDFImageReader imported into the PDFKnowledgeBase class

### ISSUE THREAD

**Issue by sridharaiyer** [phidatahq/phidata#974]
I updated `phidata` to `2.4.13`, but I am not seeing the `PDFImageReader` class imported into the `PDFKnowledgeBase` class

Here is the screenshot

<img width="1041" alt="image" src="https://github.com/phidatahq/phidata/assets/5684178/3744f618-7f98-4317-9d0c-42d4b60e6f58">

**Comment by ysolanky** [comment]
Hey @sridharaiyer, version 2.4.13 does include `PDFImageReader` and `PDFUrlImageReader`. It seems like the project that you have open in your IDE isn’t updated to 2.4.13. You can confirm via Github source code

**Comment by sridharaiyer** [comment]
Kindly look at the `pip list` command in the screenshot. I am using the the 2.2.13 version. I even deleted and recreated a virtual environment. Didn't help. Then I tried to point to the conda phidata environment that I had created to run your cookbooks. Didn't help.

**Comment by ysolanky** [comment]
@sridharaiyer 2.4.14 is out. Try using `pip install -U phidata` again.

**Comment by sridharaiyer** [comment]
Outstanding!! Only the new update, `2.4.14` fixed this issue. Thank you so much 🙏🏼
