### ISSUE TITLE
Unable to use tools with AWS Claude

### ISSUE THREAD

**Issue by subhashnaidu** [phidatahq/phidata#977]
I'm trying to use Claude Sonnet hosted on AWS Bedrock.
The tools that I pass in to the assistant are never used. 
It hallucinates function name and parameters and never actually calls any function.

This example from the cookbook modified to use the Claude assistant never calls the DuckDuckGo tool.

```python
from phi.assistant import Assistant
from phi.llm.aws.claude import Claude
from phi.tools.duckduckgo import DuckDuckGo
from dotenv import load_dotenv

load_dotenv()

assistant = Assistant(llm=Claude(model="anthropic.claude-3-sonnet-20240229-v1:0",temperature=0.2), tools=[DuckDuckGo()], show_tool_calls=True, read_chat_history=True)
assistant.cli_app(markdown=True)

```

**Comment by ysolanky** [comment]
Hi @subhashnaidu,

Claude has recently updated the tool calling format. We will be implementing these updates on our end soon.

**Comment by praveenc** [comment]
Hi @ysolanky, Is this on the roadmap anytime soon? Can't use tools with Claude on Amazon Bedrock. Would be nice. Thanks
