### ISSUE TITLE
Cant able to store content in the file using shell tools

### ISSUE THREAD

**Issue by vdsasi** [phidatahq/phidata#978]
![image](https://github.com/phidatahq/phidata/assets/94822289/e611242c-960e-4e4d-9b9a-507e9f654b81)

I am using local model openhermes. I am able to get back response that file created successfully but the file content is not there as expected. I want to store the text 'testing' into the file test.txt but it didn't worked.

**Comment by ysolanky** [comment]
Hey @vdsasi. I am not able to reproduce this issue with `GPT-4o` as my LLM. It looks like `openhermes` is not sending the right params to the `run_shell_command` function

**Comment by vdsasi** [comment]
> Hey @vdsasi. I am not able to reproduce this issue with `GPT-4o` as my LLM. It looks like `openhermes` is not sending the right params to the `run_shell_command` function

Do it works only with GPT-4o

**Comment by jacobweiss2305** [comment]
@vdsasi as of now we aren't supporting openhermes. As we get more interest we will add to our Model class. Currently we support Llama 3.1 for Ollama
