### ISSUE TITLE
pubmed tool not declaring requests as a dependency

### ISSUE THREAD

**Issue by martolini** [phidatahq/phidata#980]
<img width="747" alt="image" src="https://github.com/phidatahq/phidata/assets/2552277/23ef6748-480d-4af3-a8b5-f882aa2d1953">

Noticed that `requests` aren't specified as a dependency here, might be more people running into this.

**Comment by ysolanky** [comment]
Thanks for bringing this to our attention @martolini!

@jacobweiss2305 should we just switch to `httpx` instead?
