### ISSUE TITLE
Temperature of 0 treated as NOT_GIVEN OpenAIChat

### ISSUE THREAD

**Issue by Tesla2000** [phidatahq/phidata#988]
Greatings I bielieve I have found an issue in you code. Your current way of providing model temperature doesn't account for it being set to 0 and treats it as if it was not set instead.
![image](https://github.com/phidatahq/phidata/assets/90644163/c40c6026-7403-403a-addc-c99b7c4f07a5)
There is a similar story with seed

**Comment by jacobweiss2305** [comment]
Ah thank you. Just tested this out
```
>>> "yes" if 0 else "no"
'no'
``
