### ISSUE TITLE
Tackle RAG long pdfs pages by using more than an Agent

### ISSUE THREAD

**Issue by khalilxg** [phidatahq/phidata#990]
Tackle RAG long pdfs pages by using more than an Agent:

I was wondering if Phidatahq lets you build more than an Agent, each agent has 5k pdf page, and the user can select the agent according to topic.

Other question how phidata can store the pdfs for everytime use. 

How to use phidata for production, 100 users simultaniously, what other tools it requires thank you, this if my final year project ! :DDDDD

**Comment by jacobweiss2305** [comment]
Yes please see: https://docs.phidata.com/agents#team-of-agents
