### ISSUE TITLE
the way to specify a function is blurry

### ISSUE THREAD

**Issue by ju1987yetchung** [phidatahq/phidata#991]
![image](https://github.com/phidatahq/phidata/assets/115963979/0cfd004e-0f02-47f3-b27c-2dd09e471c18)

According the documentation, I wrote my code as below:

`from phi.assistant import Assistant
from phi.llm.ollama import Ollama

def showcase():
    """
    if let use showcase, you should use showcase
    :return:
    """
    a=1
    print(a)
    print("+++++++++")
    b=2
    print(b)
    print("+++++++++")
    print("hello, if you see me, it means function call is under implementation")

assistant = Assistant(
    llm=Ollama(model="llama3:8b"),
    #description="you are an assistant that can use function tools to reply",
    #instructions=["when people say something you need choose right function to solve problem or reply"],

    # Add functions or Toolkits
    tools=[showcase],
    tool_choice="auto",
    use_tools = True,
    # Show tool calls in LLM response.
    show_tool_calls=True,

    debug_mode=False,
)

assistant.print_response("Could you use showcase to let me check whether it is useful, thank you!") # , markdown=True)`

but when I run this code, there is 50% chance that code runing in healthy way, but another 50% chance that return error like below:

![image](https://github.com/phidatahq/phidata/assets/115963979/7a99a3e0-bbec-4674-9643-774df1e98c42)

I think it is because when I run the code, 50% chance the assistant choose not run the tool but reply directly.
So, I want force the assistant to use the tool. and changed the parameter: **tool_choice={"type": "function","function": {"name": "showcase"}}**

I don't know whether I wrote in the right way, but after runing, there is still old problem. did I wrote "tool_choice" in wrong format. What the right format be?

**Comment by jacobweiss2305** [comment]
Please see: https://docs.phidata.com/tools/functions#functions

Let me know if this works for you!
