### ISSUE TITLE
How to use Groq API?

### ISSUE THREAD

**Issue by gamercoder153** [phidatahq/phidata#993]
How to use Groq API?

**Comment by picografix** [comment]
refer these https://docs.phidata.com/llms/groq

**Comment by gamercoder153** [comment]
@picografix just ran that and got this error `groq` not installed I installed it correctly

**Comment by gamercoder153** [comment]
@picografix one more question is there a way to make the assistants talk like iterating over and over again to get desired output

**Comment by ashpreetbedi** [comment]
Hi there, please can you run `pip install groq==0.5.0`, the new 0.8.0 release broke the integration and we're working on a fix as we speak

**Comment by ashpreetbedi** [comment]
just fixed in phidata v2.4.17, please install using `pip install -U phidata`

**Comment by gamercoder153** [comment]
@ashpreetbedi is the latest groq working now
