### ISSUE TITLE
`groq` not installed

### ISSUE THREAD

**Issue by gamercoder153** [phidatahq/phidata#994]
`groq` not installed error for this code 

`from phi.assistant import Assistant
from phi.llm.groq import Groq

assistant = Assistant(
    llm=Groq(model="mixtral-8x7b-32768"),
    description="You help people with their health and fitness goals.",
    # debug_mode=True,
)
assistant.print_response("Share a quick healthy breakfast recipe.", markdown=True)`

**Comment by ashpreetbedi** [comment]
hi @gamercoder153, please can you run `pip install groq==0.5.0` for now, the new 0.8.0 release broke the integrations and we are fixing it as we speak

**Comment by ashpreetbedi** [comment]
just fixed in phidata v2.4.17, please install using `pip install -U phidata`
