### ISSUE TITLE
Connection Error if function_call run too long time.

### ISSUE THREAD

**Issue by ju1987yetchung** [phidatahq/phidata#995]
I made a self-defined function as tool of the assistant.
the self-defined function is a program of train a simple neural network. if this functiong is running, it cost about 30 minitues.
phidata can call this function easily, but during the running of this self-defined function, phidata will give a error and stop:
![image](https://github.com/phidatahq/phidata/assets/115963979/05270dd0-59a6-49e2-a94a-219a185dd1e9)
I think it is because there is limitation of time cost of the response. And I want to change this limitation to a longer time.
Could you tell me where is this definition? Thank you all！

**Comment by ysolanky** [comment]
Hey @ju1987yetchung! This error is being raised by Streamlit. I found a discussion on their forum related to your [issue](https://discuss.streamlit.io/t/frustrated-streamlit-frontend-disconnects-from-apps-with-long-running-processes/11612/21)

Out of all the solutions listed I think the one that would work best for your use case of training a NN would be to send progress updates to the Streamlit front end. Maybe after each epoch of training?

**Comment by ju1987yetchung** [comment]
> Hey @ju1987yetchung! This error is being raised by Streamlit. I found a discussion on their forum related to your [issue](https://discuss.streamlit.io/t/frustrated-streamlit-frontend-disconnects-from-apps-with-long-running-processes/11612/21)
> 
> Out of all the solutions listed I think the one that would work best for your use case of training a NN would be to send progress updates to the Streamlit front end. Maybe after each epoch of training?

Thank you Sir, I think I understand it. I will try to give some response to Streamit when I calling the function. Your reply is very helpful, thank you!
